#!/usr/bin/env python3
"""Regenerate LiteLLM's model_list from what LM Studio actually has.

    python3 tools/ai_models.py            # report
    python3 tools/ai_models.py --write    # rewrite ai/litellm/config.yaml

WHY A TOOL. Model ids are whatever LM Studio decided when the model was
downloaded -- "qwen/qwen3-vl-8b", "minicpm-v-4.6-abliterated-and-disinhibited"
-- and a mismatch is a 404 from the proxy that reads exactly like a broken
bridge. Guessing them cost time once already. This asks.

Every vision-capable model becomes a named entry, so trying one is
./bindDaemons.sh --ai --model <name> rather than a config edit and a reload.
"""
import json, os, re, subprocess, sys, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CFG  = os.path.join(ROOT, "ai", "litellm", "config.yaml")
HOST = os.environ.get("DAEMONS_LLM_HOST", "roverbyteseer")
WRITE = "--write" in sys.argv

#  Vision is not optional: every decision carries a screenshot.
VISION = re.compile(r"(vl|-v-|minicpm-o|gemma-3)", re.I)


def lmstudio_models():
    url = "http://%s:1234/api/v0/models" % HOST
    try:
        d = json.load(urllib.request.urlopen(url, timeout=8))
    except Exception:
        #  LM Studio binds loopback, so ask over ssh when we are not on the box
        r = subprocess.run(["ssh", "-o", "BatchMode=yes", "roverbyte@" + HOST,
                            "curl -fsS --max-time 8 http://127.0.0.1:1234/api/v0/models"],
                           capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit("could not reach LM Studio on %s" % HOST)
        d = json.loads(r.stdout)
    return [(m.get("id"), m.get("quantization"), m.get("state")) for m in d.get("data", [])]


def short(mid):
    """A stable short name for --model: the last path segment, cleaned."""
    s = mid.split("/")[-1].lower()
    s = re.sub(r"-(abliterated.*|and-disinhibited)$", "", s)
    return re.sub(r"[^a-z0-9]+", "-", s).strip("-")


def main():
    models = lmstudio_models()
    vis = [(i, q, st) for i, q, st in models if i and VISION.search(i)]
    print("  vision models LM Studio reports:")
    for i, q, st in vis:
        print("    %-46s %-8s %s" % (i, q or "?", st or ""))
    if not vis:
        sys.exit("  no vision-capable models found -- the decision seat needs one")

    entries = []
    for i, q, _ in vis:
        entries.append("""  - model_name: %s
    litellm_params:
      model: openai/%s
      api_base: http://127.0.0.1:1234/v1
      api_key: none
      use_chat_completions_api: true
""" % (short(i), i))

    print("\n  would define: %s" % ", ".join(short(i) for i, _, _ in vis))
    if not WRITE:
        print("\n  (report only; pass --write)")
        return

    cfg = open(CFG).read()
    marker = "# ---- generated by tools/ai_models.py ----"
    block = marker + "\n" + "".join(entries) + "# ---- end generated ----\n"
    if marker in cfg:
        cfg = re.sub(re.escape(marker) + r".*?# ---- end generated ----\n", block, cfg, flags=re.S)
    else:
        cfg = cfg.replace("litellm_settings:", block + "\nlitellm_settings:", 1)
    open(CFG, "w").write(cfg)
    print("\n  written %s" % CFG)


if __name__ == "__main__":
    main()
