#!/usr/bin/env python3
"""What the hardware gives you, measured rather than remembered.

    python3 tools/gbabudget.py [--write]

Every number in docs/engine.md's tables comes out of here, because a number in
prose drifts the moment anything moves and nobody notices until a build breaks.
Same rule the rest of tools/ runs on: PROSE IS AUTHORED, MEASUREMENTS ARE
DERIVED -- so engine.md carries the reasoning by hand and this writes the
figures into a fenced block inside it.

Three sources, none of them a guess:

  * the LINKER MAP, for what actually landed in each memory and which files
    are the biggest tenants. Written by the last link of each target, so all
    four are read and the release ROM is the one quoted.
  * the HEADERS, for every fixed-width name budget -- and the widest name we
    actually ship in each, so the headroom is visible.
  * UPSTREAM'S OWN TEXT, for the pixel budgets. Vanilla never overflows its own
    windows, so the widest line it ships in a pane IS that pane's ceiling. That
    is how the item box turned out to be 198px and the dex line 234, and it is
    the only honest way to get a number the hardware never states.

--write is the only thing that touches docs/engine.md, and it only ever
replaces what is between the two GENERATED markers.
"""
import os, re, subprocess, sys, io, contextlib, importlib.util

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
GBA  = os.path.join(ROOT, "engineGba")
DOC  = os.path.join(ROOT, "docs", "engine.md")

BEGIN = "<!-- GENERATED by tools/gbabudget.py -- do not edit between these markers -->"
END   = "<!-- END GENERATED -->"


def textwidth():
    """port_vocab owns the font metrics; borrow them rather than re-derive."""
    argv, sys.argv = sys.argv, ["port_vocab"]
    try:
        spec = importlib.util.spec_from_file_location("pv", os.path.join(HERE, "port_vocab.py"))
        pv = importlib.util.module_from_spec(spec)
        with contextlib.redirect_stdout(io.StringIO()):
            try:
                spec.loader.exec_module(pv)
            except SystemExit:
                pass
        return pv.textwidth
    finally:
        sys.argv = argv


def upstream(path):
    r = subprocess.run(["git", "-C", GBA, "show", "upstream/master:" + path],
                       capture_output=True, text=True)
    return r.stdout if r.returncode == 0 else ""


def read(path):
    p = os.path.join(GBA, path)
    return open(p, encoding="utf-8", errors="ignore").read() if os.path.exists(p) else ""


# --------------------------------------------------------------- the memories
REGIONS = [("EWRAM", 256 * 1024), ("IWRAM", 32 * 1024), ("ROM", 32 * 1024 * 1024)]


def memory(mapname):
    """--print-memory-usage is a build-time nicety and is not in the map, so
    the sections are added up from the map itself."""
    path = os.path.join(GBA, mapname)
    if not os.path.exists(path):
        return None
    lines = open(path, errors="ignore").read().split("\n")
    out = {}
    for name in ("ewram", "iwram"):
        for l in lines:
            m = re.match(r'^%s\s+0x[0-9a-f]+\s+0x([0-9a-f]+)' % name, l)
            if m:
                out[name.upper()] = int(m.group(1), 16)
                break
    #  NOT the .gba file size: objcopy pads every build to a flat 16 MB, so
    #  that number is the same whatever the ROM contains. The linker's figure
    #  is the HIGH-WATER MARK in the cartridge region, and reconstructing it
    #  from the map agrees with --print-memory-usage to the byte.
    hi = 0
    for m in re.finditer(r'0x08([0-9a-f]{6})\s+0x([0-9a-f]+)\b', "\n".join(lines)):
        addr, size = 0x08000000 + int(m.group(1), 16), int(m.group(2), 16)
        if size < 0x1000000:          # a size, not another address
            hi = max(hi, addr + size)
    if hi:
        out["ROM"] = hi - 0x08000000
    return out


def tenants(mapname, section, limit=6):
    """The biggest single contributors, so the answer to 'what is in there'
    is a list of files rather than a shrug."""
    path = os.path.join(GBA, mapname)
    lines = open(path, errors="ignore").read().split("\n")
    try:
        start = next(i for i, l in enumerate(lines) if l.startswith(section + " "))
    except StopIteration:
        return []
    rows, pat = [], re.compile(r'^ (?:ewram_data|\.bss|COMMON|\.bss\.code)\s+0x0[0-9a-f]{7}\s+0x([0-9a-f]+)\s+(\S+)')
    for l in lines[start + 1:]:
        if l and not l.startswith(" ") and not l.startswith(section):
            break
        m = pat.match(l)
        if m:
            rows.append((int(m.group(1), 16), m.group(2)))
    rows.sort(reverse=True)
    return rows[:limit]


HEAP = None
def heap():
    global HEAP
    if HEAP is None:
        m = re.search(r'#define HEAP_SIZE\s+(0x[0-9A-Fa-f]+)', read("include/malloc.h"))
        HEAP = int(m.group(1), 16) if m else 0
    return HEAP


# ---------------------------------------------------------- the name budgets
def constants():
    txt = read("include/constants/global.h") + read("include/battle_main.h")
    c = dict((k, int(v)) for k, v in re.findall(r'#define (\w+_NAME_LENGTH)\s+(\d+)', txt))
    # A fixed-size array declares its own limit and agbcc reports an overflow
    # as "excess elements in array initializer", which does not name the string.
    for path, pat, key in (
        ("include/data.h",    r'gTrainerClassNames\[\]\[(\d+)\]', "TRAINER_CLASS"),
        ("include/pokedex.h", r'categoryName\[(\d+)\]',           "DEX_CATEGORY"),
        ("include/battle.h",  r'trainerName\[(\d+)\]',            "TRAINER_NAME"),
    ):
        m = re.search(pat, read(path))
        if m:
            c[key] = int(m.group(1))
    return c


#  The cap comes from the ARRAY DECLARATION, never from the constant on its
#  own -- because the two families do not agree. gSpeciesNames is
#  [POKEMON_NAME_LENGTH + 1], so the constant IS the character count; but
#  ItemInfo's name is [ITEM_NAME_LENGTH], so there the constant is one MORE
#  than the count. Reading the declaration removes the need to remember which
#  is which, and would follow the header if either ever changed.
#
#  (label, where the array is declared, the width expression, the table, an entry)
NAME_TABLES = [
    ("species",       "include/data.h",       r'gSpeciesNames\[\]\[([^\]]+)\]',       "src/data/text/species_names.h",       r'\[SPECIES_\w+\] = _\("([^"]*)"\)'),
    ("routine",       "include/data.h",       r'gMoveNames\[\]\[([^\]]+)\]',          "src/data/text/move_names.h",          r'\[MOVE_\w+\]\s*=\s*_\("([^"]*)"\)'),
    ("register",      "include/battle_main.h",r'gAbilityNames\[[^\]]*\]\[([^\]]+)\]',       "src/data/text/abilities.h",           r'\[ABILITY_\w+\] = _\("([^"]*)"\)'),
    ("type",          "include/battle_main.h", r'gTypeNames\[[^\]]*\]\[([^\]]+)\]',          "src/battle_main.c",                   r'\[TYPE_\w+\] = _\("([^"]*)"\)'),
    ("trainer class", "include/data.h",       r'gTrainerClassNames\[\]\[([^\]]+)\]',  "src/data/text/trainer_class_names.h", r'_\("([^"]*)"\)'),
    ("dex category",  "include/pokedex.h",    r'categoryName\[([^\]]+)\]',              "src/data/pokemon/pokedex_entries.h",  r'\.categoryName = _\("([^"]*)"\)'),
    ("trainer name",  "include/battle.h",     r'trainerName\[([^\]]+)\]',               "src/data/trainers.h",                 r'\.trainerName = _\("([^"]*)"\)'),
    ("item",          "include/item.h",       r'name\[([^\]]+)\]',                      "src/data/items.json",                 r'"english":\s*"([^"]*)"'),
]


def cap_from_decl(header, pat, consts):
    """[X + 1] means X characters; [X] and [12] mean one less than X."""
    m = re.search(pat, read(header))
    if not m:
        return None
    expr = m.group(1).strip()
    plus = expr.endswith("+ 1")
    base = expr[:-3].strip() if plus else expr
    n = int(base) if base.isdigit() else consts.get(base)
    if n is None:
        return None
    return n if plus else n - 1


#  Placeholders and control codes are not names. "??????????" is vanilla's
#  blank species slot and "{POKEBLOCK} CASE" is one glyph wearing eleven
#  characters -- counting either as the widest hides the real one.
def real_names(names):
    return [n for n in names
            if n and "{" not in n and set(n) - set("?- ")]

# Where a line of text has to fit, and the vanilla file the ceiling is read out
# of. The pane is never told to us by the hardware; vanilla's own widest line is.
PANES = [
    ("item description",  "src/data/items.json",                 r'"description_english":\s*"([^"]*)"'),
    ("routine descript.", "src/move_descriptions.c",             r'_\("([^"]*)"\)'),
    ("Index entry line",  "src/data/pokemon/pokedex_text_fr.h",  r'_\(\s*((?:"[^"]*"\s*)+)\)'),
]


def widest(text, pat, tw):
    best, who = 0, ""
    for m in re.finditer(pat, text):
        body = m.group(1)
        for piece in re.split(r'\\[npl]', "".join(re.findall(r'"([^"]*)"', body)) if body.startswith('"') else body):
            piece = piece.replace("$", "")
            if not piece:
                continue
            w = tw(piece)
            if w > best:
                best, who = w, piece
    return best, who


def main():
    tw = textwidth()
    out = []
    out.append(BEGIN)
    out.append("")
    out.append("### The three memories")
    out.append("")
    out.append("| | size | used | free | %age |")
    out.append("|---|---|---|---|---|")
    rel = memory("pokefirered.map")
    for name, size in REGIONS:
        used = rel.get(name, 0)
        out.append("| **%s** | %s | %s | **%s** | %.2f%% |"
                   % (name, kb(size), kb(used), kb(size - used), 100.0 * used / size))
    out.append("")
    dbg = memory("pokefirered_debug.map")
    if dbg:
        out.append("*The debug ROM costs a further **%d bytes** of EWRAM and **%d** of IWRAM.*"
                   % (dbg.get("EWRAM", 0) - rel.get("EWRAM", 0),
                      dbg.get("IWRAM", 0) - rel.get("IWRAM", 0)))
        out.append("")
    out.append("**`gHeap` alone is %s of EWRAM** — %.0f%% of the whole region, reserved at address zero "
               "and carved up at runtime by `Alloc`." % (kb(heap()), 100.0 * heap() / (256 * 1024)))
    out.append("")
    out.append("The biggest tenants after it:")
    out.append("")
    out.append("| EWRAM | | IWRAM | |")
    out.append("|---|---|---|---|")
    e, i = tenants("pokefirered.map", "ewram"), tenants("pokefirered.map", "iwram")
    for n in range(max(len(e), len(i))):
        a = "`%s` | %s" % (e[n][1], kb(e[n][0])) if n < len(e) else " | "
        b = "`%s` | %s" % (i[n][1], kb(i[n][0])) if n < len(i) else " | "
        out.append("| %s | %s |" % (a, b))
    out.append("")

    out.append("### Every fixed-width name budget, and what we actually ship")
    out.append("")
    out.append("| surface | characters | widest of ours | headroom |")
    out.append("|---|---|---|---|")
    c = constants()
    for label, header, decl, path, pat in NAME_TABLES:
        budget = cap_from_decl(header, decl, c)
        names = real_names(re.findall(pat, read(path)))
        if budget is None or not names:
            print("  !! %s: no cap or no names" % label)
            continue
        longest = max(names, key=len)
        flag = "" if len(longest) <= budget else " **OVER**"
        out.append("| %s | **%d** | `%s` (%d) | %d%s |"
                   % (label, budget, longest, len(longest), budget - len(longest), flag))
    out.append("")
    out.append("*Character counts, not pixels: these are arrays, and agbcc reports an overflow as "
               "\"excess elements in array initializer\", which never names the string.*")
    out.append("")

    out.append("### Every pane, against the widest line vanilla puts in it")
    out.append("")
    out.append("*Vanilla never overflows its own window, so its widest line is a **demonstrated safe "
               "width** — a floor, not a ceiling. Ours being wider is a thing to look at, not "
               "automatically a bug.*")
    out.append("")
    out.append("| pane | vanilla's widest | ours | |")
    out.append("|---|---|---|---|")
    for label, path, pat in PANES:
        up = upstream(path)
        if not up:
            continue
        vw, _ = widest(up, pat, tw)
        ow, line = widest(read(path), pat, tw)
        note = "%d to spare" % (vw - ow) if ow <= vw else "**%dpx past it** — `%s`" % (ow - vw, line[:34])
        out.append("| %s | **%dpx** | %dpx | %s |" % (label, vw, ow, note))
    out.append("")
    out.append(END)
    body = "\n".join(out)

    print("  EWRAM %d / %d, IWRAM %d / %d, ROM %.1f MB"
          % (rel.get("EWRAM", 0), 256 * 1024, rel.get("IWRAM", 0), 32 * 1024,
             rel.get("ROM", 0) / 1048576.0))
    print("  %d name budgets, %d panes" % (len(NAME_TABLES), len(PANES)))

    if "--write" in sys.argv:
        if not os.path.exists(DOC):
            print("  !! %s does not exist yet" % DOC); return 1
        doc = open(DOC, encoding="utf-8").read()
        if BEGIN not in doc or END not in doc:
            print("  !! markers missing in docs/engine.md"); return 1
        head, rest = doc.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        open(DOC, "w", encoding="utf-8").write(head + body + tail)
        print("  written %s" % os.path.relpath(DOC, ROOT))
    else:
        print("  (report only; pass --write)")
    return 0


def kb(n):
    if n >= 1048576:
        return "%.1f MB" % (n / 1048576.0)
    if n >= 1024:
        return "%.1f KB" % (n / 1024.0)
    return "%d B" % n


if __name__ == "__main__":
    sys.exit(main())
