#!/usr/bin/env python3
"""The day's colour, on the CHECKPOINT's trim (T-275; decided by the user 2026-09-25).

    python3 tools/gbadaytrim.py            # report: each day's trim and its distance from the nearest type hue
    python3 tools/gbadaytrim.py --write    # engineGba/src/data/day_trims.h

"I do want some colour representation, perhaps just the trim on the checkpoint changes based on the day ...
something subtle." The user's seven are the rainbow in order, Sunday red to Saturday violet (with the notes C to B,
T-274), which is the Guide's order too (Chapters 8-9).

WHAT CHANGES. The CHECKPOINT rotunda (gbacivic.py) draws its trim -- the band round the dome's base, the courses,
the canopy over the door -- in General palette row 2, index 8 (TEALD), which nothing else draws. fieldmap.c puts the
day's colour in that one slot as the palette loads, before the watch's tint, so dusk and night fall on it like on
everything else. Nothing names it.

THE RULE IT MUST KEEP (9.4): no UI colour may sit on a type's hue, measured as genguide.py measures it -- 20 or more
(CIE76) from every one of the 18 type colours. The rainbow does not keep it by itself: a plain orange sits on
ENTROPY and a plain red near VECTOR (the Guide's own measurements). So each day starts from its rainbow hue at the
trim's own lightness and moderate saturation -- a trim, not a sign -- and the nearest colour that clears every type
by the margin is taken, searching outward in hue, then saturation, then lightness. Checked in the GBA's own
5-bit-per-channel colour, which is what the screen shows.
"""
import colorsys, importlib.util, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "engineGba/src/data/day_trims.h")
WRITE = "--write" in sys.argv
spec = importlib.util.spec_from_file_location("genguide", os.path.join(ROOT, "tools", "genguide.py"))
G = importlib.util.module_from_spec(spec)
spec.loader.exec_module(G)

MARGIN = 22                      # 9.4 says 20; two more so a 5-bit rounding can never land on the line
DAYS = [("SUNDAY", "C", 0), ("MONDAY", "D", 30), ("TUESDAY", "E", 55), ("WEDNESDAY", "F", 120),
        ("THURSDAY", "G", 210), ("FRIDAY", "A", 245), ("SATURDAY", "B", 285)]
TEALD = (58, 138, 140)           # the trim as gbacivic drew it; its lightness is kept
BASE_L = colorsys.rgb_to_hls(*(v / 255 for v in TEALD))[1]


def gba(c):
    """Round to the GBA's 5 bits a channel, and back to 8 as the screen shows them."""
    return tuple((v >> 3) << 3 for v in c)


def nearest_type(c, hues):
    return min((sum((a - b) ** 2 for a, b in zip(G.lab(c), G.lab(v))) ** .5, k) for k, v in hues.items())


def rgb(h, l, s):
    return tuple(int(round(v * 255)) for v in colorsys.hls_to_rgb((h % 360) / 360, l, s))


def choose(hue, hues):
    for dh in [0] + [d * sign for d in range(3, 31, 3) for sign in (1, -1)]:
        for s in (0.45, 0.38, 0.52, 0.30):
            for dl in (0, 0.04, -0.04, 0.08, -0.08):
                c = gba(rgb(hue + dh, BASE_L + dl, s))
                d, t = nearest_type(c, hues)
                if d >= MARGIN:
                    return c, d, t, dh
    raise SystemExit("  no colour near hue %d clears every type by %d" % (hue, MARGIN))


def main():
    hues = G.type_hues()
    rows = []
    for name, note, hue in DAYS:
        c, d, t, dh = choose(hue, hues)
        rows.append((name, note, c))
        print("  %-9s %s  rgb%-15s %4.1f from %-8s%s" % (name, note, c, d, t, "" if not dh else "  (hue moved %+d)" % dh))
    text = ("// Generated by tools/gbadaytrim.py -- do not edit. T-275: the CHECKPOINT's trim, one colour a day,\n"
            "// Sunday first; each 22+ (CIE76) from every type's hue (9.4).\n"
            "static const u16 sDayTrims[] = {\n" +
            "".join("    RGB(%d, %d, %d),   // %s, %s\n" % (c[0] >> 3, c[1] >> 3, c[2] >> 3, n, note)
                    for n, note, c in rows) + "};\n")
    old = open(OUT).read() if os.path.exists(OUT) else None
    if old == text:
        print("  day_trims.h already written")
    elif WRITE:
        open(OUT, "w").write(text)
        print("  written")
    else:
        print("  day_trims.h to write")
    return 0


if __name__ == "__main__":
    sys.exit(main())
