#!/usr/bin/env python3
"""QR codes at the end of the pages that came from the user's writing (T-315).

    python3 tools/gbaqr.py            # report
    python3 tools/gbaqr.py --write    # engineGba/src/data/qr_codes.h

The user, 2026-09-26: FOLDS, the GUIDE and pages like them could end on a QR code -- to the SeeingSharp post, later
the book, or a repo where the in-game text can be read on a phone. A QR code is a picture, so the book reader draws
it from a bitmap, one module a 2x2 block, on a quiet zone of its own (book_reader.c). Nothing on the page says what
it is (craft rule 1): a player who scans it finds out.

    FOLDS  -> the essay on Seeing Sharp (lineage.md 5)
    GUIDE  -> the Guide's text in this repository, which is what the game prints -- until the book is out

Needs the `qrcode` package (pip install qrcode). Error correction L: the smallest code, and a screen is not a
scuffed poster.
"""
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "engineGba", "src", "data", "qr_codes.h")
WRITE = "--write" in sys.argv

CODES = [
    ("Folds", "https://seeingsharpca.wordpress.com/2025/09/05/%f0%9f%95%8a%ef%b8%8f-the-folds-of-awareness/"),
    ("Guide", "https://github.com/CodeMusic/DAEMONS/blob/main/docs/guide.md"),
]


def matrix(url):
    import qrcode
    q = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_L, border=0)
    q.add_data(url)
    q.make(fit=True)
    return q.get_matrix()


def header():
    out = ["//  GENERATED by tools/gbaqr.py (T-315) -- edit that, not this.",
           "//  Each code: its size in modules, then one row after another, eight modules a byte, high bit first.", ""]
    for name, url in CODES:
        m = matrix(url)
        n = len(m)
        data = [n]
        for row in m:
            for b in range(0, n, 8):
                v = 0
                for k in range(8):
                    if b + k < n and row[b + k]:
                        v |= 0x80 >> k
                data.append(v)
        out.append("//  %s" % url)
        body = ", ".join("0x%02X" % v for v in data)
        out.append("static const u8 sQr_%s[] = { %s };" % (name, body))
        out.append("")
    return "\n".join(out)


def main():
    text = header()
    for name, url in CODES:
        print("  %-6s %2d modules  %s" % (name, len(matrix(url)), url))
    old = open(OUT).read() if os.path.exists(OUT) else None
    if old == text:
        print("  qr_codes.h is current")
        return
    if not WRITE:
        print("  report only; pass --write")
        return
    open(OUT, "w").write(text)
    print("  written  src/data/qr_codes.h")


if __name__ == "__main__":
    main()
