#!/usr/bin/env python3
"""THE SEASONS' COLOURS, for the game (T-359; the user approved the mock-ups 2026-10-03: "build as mocked").

    python3 tools/gbaseasons.py            # report
    python3 tools/gbaseasons.py --write    # src/data/season_palettes.h

The tables come from tools/seasonmock.py's own season functions, so the game draws exactly what was approved: for
each season, gTileset_General's palette 0 with its tree, grass and petal slots replaced, and the entries of General's
rows 1..6 that are exact copies of those greens (the edges of paths and ponds draw the grass from there) replaced
the same way. Only General's own rows: a town's secondary palette is never matched by colour, so a green roof
somewhere cannot turn amber by coincidence. Summer is the palette as drawn and has no table.
"""
import importlib.util, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GBA = os.path.join(ROOT, "engineGba")
OUT = os.path.join(GBA, "src/data/season_palettes.h")
WRITE = "--write" in sys.argv

_argv, sys.argv = sys.argv, sys.argv[:1]
_spec = importlib.util.spec_from_file_location("seasonmock", os.path.join(ROOT, "tools/seasonmock.py"))
SM = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(SM)
sys.argv = _argv

ORDER = ("winter", "spring", "summer", "autumn")       # SEASON_WINTER .. SEASON_AUTUMN, as daemons_time.h numbers them


def rgb5(c):
    return c[0] | c[1] << 5 | c[2] << 10


def main():
    pd = SM.C.tdir("gTileset_General", "primary")
    rows = [SM.C.read_pal(os.path.join(pd, "palettes/%02d.pal" % r)) for r in range(7)]
    SM.PAL0 = rows[0]
    slots = sorted(SM.TREES + SM.GRASS + SM.PETALS)
    greens = {SM.to5(rows[0][i]): i for i in SM.TREES + SM.GRASS}
    follow = [(r * 16 + i, greens[SM.to5(c)]) for r in range(1, 7) for i, c in enumerate(rows[r])
              if i and SM.to5(c) in greens]
    tables = {s: SM.season_table(s) for s in ORDER if s != "summer"}

    out = ["//  Generated by tools/gbaseasons.py -- edit the tool (and the looks, in tools/seasonmock.py), not this file.",
           "//  T-359: the seasons, by palette (vision.md 9.21). Each table is gTileset_General's palette 0 in that season;",
           "//  sSeasonFollow names the entries of General's rows 1..6 that copy one of its greens, and which slot they copy.",
           "",
           "#define SEASON_SLOT_MASK 0x%04X   // palette 0's slots a season replaces: %s" % (
               sum(1 << i for i in slots), ", ".join(map(str, slots))),
           "",
           "static const u16 sSeasonRow0[SEASON_COUNT][16] =",
           "{"]
    for s in ORDER:
        t = tables.get(s)
        body = ", ".join("0x%04X" % rgb5(c) for c in t) if t else "0"
        out.append("    [SEASON_%s] = { %s }," % (s.upper(), body))
    out += ["};", "", "static const u8 sSeasonFollow[][2] =   // { BG palette index, the row 0 slot it copies }", "{"]
    out += ["    { %d, %d }," % f for f in follow]
    out += ["};", ""]
    text = "\n".join(out)
    old = open(OUT).read() if os.path.exists(OUT) else None
    print("  %d slots a season; %d entries of rows 1..6 follow them; %s" % (len(slots), len(follow), [f for f in follow]))
    if old == text:
        print("  season_palettes.h is up to date")
    elif WRITE:
        open(OUT, "w").write(text)
        print("  written %s" % os.path.relpath(OUT, ROOT))
    else:
        print("  season_palettes.h would change -- run with --write")
    return 0


if __name__ == "__main__":
    sys.exit(main())
