#!/usr/bin/env python3
"""T-389, T-390 (bible 0.7, Wisdom; the user, 2026-10-08): a MARK and its ROOT together.

Reads `docs/wisdom.json` -- every word of it DRAFT -- and writes three things into the GBA engine:

  1. each of the seven BENCHMARKS' text.inc: the leader's lines after the win, without the paired understanding and
     with it, the union PLUGIN handed over, and what it does;
  2. each BENCHMARK's scripts.inc: `<Map>_EventScript_Wisdom`, which the leader's talk-again branch goes to (that one
     `goto` is written by hand in each gym, and this tool refuses to run if it is missing). Without the
     understanding: what the MARK taught and where to come back understanding. With it: the two together, and the
     PLUGIN, once;
  3. `src/data/wisdom.h`: the seven insights -- the NOTEBOOK's INSIGHT section (notebook.c) and the line that arrives
     on the first step after a MARK and its understanding are both held (field_control_avatar.c).

Every box is wrapped to the message box's 208px in the game's own font; a line that will not fit stops the run.
The blocks it owns sit between `@ BEGIN gbawisdom` and `@ END gbawisdom`, so a rerun replaces them and nothing else.

  python3 tools/gbawisdom.py            # report what would change
  python3 tools/gbawisdom.py --write
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from genguide import width  # noqa: E402  (the game's font, read from the engine)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GBA = os.path.join(ROOT, "engineGba")
SRC = os.path.join(ROOT, "docs", "wisdom.json")
HEADER = os.path.join(GBA, "src", "data", "wisdom.h")
BOX = 208
BEGIN, END = "@ BEGIN gbawisdom", "@ END gbawisdom"
GIVE = ("Take this.", "Here!")


def wrap(text, w=BOX):
    lines, cur = [], ""
    for word in text.split():
        cand = (cur + " " + word).strip()
        if width(cand) <= w:
            cur = cand
        else:
            if not cur:
                sys.exit("gbawisdom: %r is wider than %dpx on its own" % (word, w))
            lines.append(cur)
            cur = word
    lines.append(cur)
    return lines


def box_string(paragraphs):
    """Paragraphs -> one message: \\n then \\l within a paragraph, \\p between."""
    out = []
    for para in paragraphs:
        ls = wrap(para)
        out.append(ls[0] + "".join(("\\n" if i == 1 else "\\l") + l for i, l in enumerate(ls[1:], 1)))
    return "\\p".join(out)


def asm_string(label, paragraphs):
    s = box_string(paragraphs)
    return "%s::\n\t.string \"%s$\"\n" % (label, s)


def split_give(paras):
    """The 'with' lines end by handing the PLUGIN over; said again after it is given, that part is left off."""
    again = list(paras)
    last = again[-1]
    for g in GIVE:
        if last == g:
            again.pop()
        elif last.endswith(" " + g):
            again[-1] = last[: -len(g) - 1]
    return again


def gym_blocks(p):
    m = p["map"]
    text = [
        "%s -- T-389, GENERATED by tools/gbawisdom.py from docs/wisdom.json. Every word DRAFT." % BEGIN,
        asm_string("%s_Text_WisdomWithout" % m, p["without"]),
        asm_string("%s_Text_WisdomWith" % m, p["with"]),
        asm_string("%s_Text_WisdomAgain" % m, split_give(p["with"])),
        "%s_Text_ReceivedUnion::\n\t.string \"{PLAYER} received %s from\\n%s.$\"\n" % (m, p["plugin_name"], p["leader"]),
        asm_string("%s_Text_ExplainUnion" % m, p["explain"]),
        asm_string("%s_Text_WisdomNoRoom" % m, ["Make room in your TOOLKIT, and come back."]),
        END,
    ]
    script = "\n".join([
        "%s -- T-389, GENERATED by tools/gbawisdom.py from docs/wisdom.json." % BEGIN,
        "@ After the win: without the understanding, what the MARK taught and where to come back understanding;",
        "@ with it, the two together and the union PLUGIN, once (bible 0.7, Wisdom).",
        "%s_EventScript_Wisdom::" % m,
        "\tgoto_if_unset %s, %s_EventScript_WisdomNotYet" % (p["root"], m),
        "\tgoto_if_set %s, %s_EventScript_WisdomAgain" % (p["given"], m),
        "\tmsgbox %s_Text_WisdomWith" % m,
        "\tcheckitemspace %s" % p["plugin"],
        "\tgoto_if_eq VAR_RESULT, FALSE, %s_EventScript_WisdomNoRoom" % m,
        "\tgiveitem_msg %s_Text_ReceivedUnion, %s" % (m, p["plugin"]),
        "\tsetflag %s" % p["given"],
        "\tmsgbox %s_Text_ExplainUnion" % m,
        "\trelease",
        "\tend",
        "",
        "%s_EventScript_WisdomAgain::" % m,
        "\tmsgbox %s_Text_WisdomAgain" % m,
        "\trelease",
        "\tend",
        "",
        "%s_EventScript_WisdomNotYet::" % m,
        "\tmsgbox %s_Text_WisdomWithout" % m,
        "\trelease",
        "\tend",
        "",
        "%s_EventScript_WisdomNoRoom::" % m,
        "\tmsgbox %s_Text_WisdomNoRoom" % m,
        "\trelease",
        "\tend",
        END,
    ])
    return "\n".join(text) + "\n", script + "\n"


def c_text(s):
    return s.replace('"', '\\"')


def header(doc):
    out = ["// GENERATED by DAEMONS tools/gbawisdom.py from docs/wisdom.json -- do not edit by hand.",
           "// T-390 (bible 0.7, Wisdom): the seven insights, one for each MARK and its understanding held together.",
           "// Every word DRAFT. Included once, by notebook.c.",
           "#ifndef GUARD_DATA_WISDOM_H", "#define GUARD_DATA_WISDOM_H", ""]
    entries, pairs = [], []
    for p in doc["pairs"]:
        v = p["virtue"].capitalize()
        ins = wrap(p["insight"], 200)
        arrival = [doc["arrival"][0], doc["arrival"][1].replace("{INSIGHT}", p["insight"]), doc["arrival"][2]]
        out.append('static const u8 sInsightTitle_%s[] = _("%s");' % (v, p["virtue"]))
        out.append('static const u8 sInsightText_%s[] = _("%s");' % (v, c_text(" ".join(ins))))
        out.append('static const u8 sInsightArrival_%s[] = _("%s");' % (v, c_text(box_string(arrival))))
        entries.append("    { NB_INSIGHT, NB_KIND_TEXT, 0, %s, 0, sInsightTitle_%s, sInsightText_%s }," % (p["insight_flag"], v, v))
        pairs.append("    { %s, %s, %s, sInsightArrival_%s }," % (p["badge"], p["root"], p["insight_flag"], v))
    out += ["", "//  The INSIGHT section's entries, in the MARKS' order (notebook.c rule 2: the authored order, never the order found).",
            "#define NB_INSIGHT_ENTRIES \\"]
    out += [e + " \\" for e in entries]
    out += ["", "", "//  What makes each arrive: the MARK, the understanding, and the flag that says it has.",
            "struct WisdomPair { u16 mark; u16 root; u16 insight; const u8 *arrival; };",
            "static const struct WisdomPair sWisdomPairs[] =", "{"] + pairs + ["};", "", "#endif // GUARD_DATA_WISDOM_H", ""]
    return "\n".join(out)


def replace_block(path, block):
    s = open(path).read()
    if BEGIN in s:
        a = s.index(BEGIN)
        b = s.index(END, a) + len(END)
        new = s[:a] + block.rstrip("\n") + s[b:]
    else:
        new = s.rstrip("\n") + "\n\n" + block
    return s, new


def main():
    write = "--write" in sys.argv
    doc = json.load(open(SRC))
    changes = []
    for p in doc["pairs"]:
        text, script = gym_blocks(p)
        sp = os.path.join(GBA, "data", "maps", p["map"], "scripts.inc")
        if "goto %s_EventScript_Wisdom\n" % p["map"] not in open(sp).read():
            sys.exit("gbawisdom: %s's talk-again branch does not go to %s_EventScript_Wisdom -- add that goto by hand"
                     % (p["leader"], p["map"]))
        for path, block in ((os.path.join(GBA, "data", "maps", p["map"], "text.inc"), text), (sp, script)):
            old, new = replace_block(path, block)
            if old != new:
                changes.append((path, new))
    h = header(doc)
    if not os.path.exists(HEADER) or open(HEADER).read() != h:
        changes.append((HEADER, h))
    for path, new in changes:
        print("  %s %s" % ("wrote" if write else "would write", os.path.relpath(path, GBA)))
        if write:
            open(path, "w").write(new)
    if not changes:
        print("  gbawisdom: everything matches docs/wisdom.json")


if __name__ == "__main__":
    main()
