#!/usr/bin/env python3
"""The brain on the USER card, which lights and never counts (T-271; decided by the user 2026-09-25).

    python3 tools/genbrain.py            # report, and a preview to $SCRATCH/brain.png when SCRATCH is set
    python3 tools/genbrain.py --write     # engineGba/src/data/understanding_brain.h

THE DECISION. Understandings are shown in the Guide's margins (T-304), never counted (T-252). If the card shows a
brain at all, it is one glow that says something has changed -- never modules totalled. So this is one drawing with
two states: GREY until any understanding is arrived at, and LIT after, the same brain brighter with a halo. No
region lights on its own and nothing is numbered.

THE DRAWING is a brain seen from the side -- its outline, the folds of the cortex, the cerebellum's small lobe at the
back and the stem beneath -- the four regions the Guide's Chapter 1 names (processor, kernel, co-processor, operating
system), there as texture and never labelled or lit apart.

COLOUR BY BRIGHTNESS, NOT HUE. It is drawn into the card's text window, whose palette is the standard text palette,
and 9.4 keeps type hues off the interface -- so the two states differ in lightness only: grey fill and dark folds,
then white fill, grey folds and a white halo. Each cell is a role: '.' fill, 'f' fold, 'o' outline, ' ' nothing;
'h' is the halo, drawn only when lit.
"""
import math, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "engineGba/src/data/understanding_brain.h")
WRITE = "--write" in sys.argv
W, H = 26, 22


def draw():
    g = [[" "] * W for _ in range(H)]
    cx, cy, rx, ry = 12.5, 8.5, 11.2, 7.6
    inside = lambda x, y: ((x - cx) / rx) ** 2 + ((y - cy) / ry) ** 2 <= 1.0
    for y in range(H):
        for x in range(W):
            if inside(x, y):
                g[y][x] = "."
    # the cerebellum: a small lobe low at the back (right), and the stem under it
    for y in range(H):
        for x in range(W):
            if ((x - 18.5) / 4.2) ** 2 + ((y - 14.5) / 2.8) ** 2 <= 1.0:
                g[y][x] = "."
    for y in range(15, 20):
        for x in (13, 14, 15):
            g[y][x] = "."
    # the folds: short curves across the cortex, and the cerebellum's parallel lines
    folds = [[(4, 6), (6, 5), (8, 6), (9, 8)], [(11, 3), (12, 5), (14, 5), (15, 3)], [(17, 5), (19, 6), (20, 8)],
             [(5, 10), (7, 9), (9, 10), (11, 11)], [(13, 8), (15, 9), (16, 11)], [(8, 13), (10, 12), (12, 13)],
             [(17, 14), (20, 14)], [(17, 16), (20, 16)]]
    for line in folds:
        for (x0, y0), (x1, y1) in zip(line, line[1:]):
            n = max(abs(x1 - x0), abs(y1 - y0))
            for i in range(n + 1):
                x, y = round(x0 + (x1 - x0) * i / n), round(y0 + (y1 - y0) * i / n)
                if g[y][x] == ".":
                    g[y][x] = "f"
    # the outline: every empty cell beside a drawn one; then the halo, one further out
    def ring(src, mark, over):
        out = [row[:] for row in src]
        for y in range(H):
            for x in range(W):
                if src[y][x] == " " and any(0 <= y + dy < H and 0 <= x + dx < W and src[y + dy][x + dx] in over
                                            for dy, dx in ((0, 1), (0, -1), (1, 0), (-1, 0))):
                    out[y][x] = mark
        return out
    g = ring(g, "o", ".f")
    g = ring(g, "h", "o")
    return ["".join(r) for r in g]


def main():
    art = draw()
    text = ("// Generated by tools/genbrain.py -- do not edit. T-271: the USER card's brain, one drawing and two states.\n"
            "// '.' fill, 'f' fold, 'o' outline, 'h' halo (lit only), ' ' nothing.\n"
            "#define BRAIN_W %d\n#define BRAIN_H %d\n" % (W, H) +
            "static const char sUnderstandingBrain[BRAIN_H][BRAIN_W + 1] = {\n" +
            "".join('    "%s",\n' % r for r in art) + "};\n")
    for r in art:
        print("  |" + r + "|")
    if os.environ.get("SCRATCH"):
        from PIL import Image
        cols = {" ": (200, 214, 190), ".": (240, 240, 240), "f": (150, 150, 150), "o": (70, 70, 70), "h": (255, 255, 255)}
        im = Image.new("RGB", (W, H))
        im.putdata([cols[c] for r in art for c in r])
        im.resize((W * 8, H * 8), Image.NEAREST).save(os.path.join(os.environ["SCRATCH"], "brain.png"))
    old = open(OUT).read() if os.path.exists(OUT) else None
    if old == text:
        print("  understanding_brain.h already written")
    elif WRITE:
        open(OUT, "w").write(text)
        print("  written")
    else:
        print("  understanding_brain.h to write")
    return 0


if __name__ == "__main__":
    sys.exit(main())
