#!/usr/bin/env python3
"""OPUS's margin lines, wrapped to the Index entry's own pane (T-197; vision.md 4.2).

    python3 tools/genmargins.py            # report every line, measured
    python3 tools/genmargins.py --write     # write src/data/opus_margins.h

WHAT A MARGIN LINE IS. The entry measures the daemon -- height, weight, type, stats, and the thin sentence
4.2 is about. The margin notices the PLAYER, and never says so. It is never a measurement, never advice,
never a hint, and it only makes sense read against the entry above it.

TWO LINES, because what OPUS noticed depends on what you did. A daemon you levelled gets one line; a daemon
you bound and put away gets another. The second is not a scold -- it is the same quiet noticing, aimed at the
thing you did not do.

NOT EVERY ENTRY HAS ONE, and that is the point: a reader annotates where they had a thought.

THE PANE is the entry's own, demonstrated rather than declared -- 234px and four lines, which is the widest
line and the most lines the 386 entries use.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GBA = os.path.join(ROOT, "engineGba")
OUT = os.path.join(GBA, "src/data/opus_margins.h")
PANE, MAXLINES = 234, 4
WRITE = "--write" in sys.argv

_src = open(os.path.join(ROOT, "tools/port_vocab.py"), encoding="utf-8").read()
_ns = {"__name__": "port_vocab_font", "__file__": os.path.join(ROOT, "tools/port_vocab.py")}
exec(compile(_src.split("# ------------------------------------------------------- names, derived")[0],
             "port_vocab.py", "exec"), _ns)
textwidth = _ns["textwidth"]

#  (species constant, our name, carried, neglected)
MARGINS = [
    ("SPECIES_BULBASAUR", "ROVERCUB",
     "It remembers the way back to the first town. You have not gone that way in some time.",
     "It is not being carried past anything."),
    ("SPECIES_CHARMANDER", "LABEL",
     "It has met you now. It has not changed the answer.",
     "It is still holding the one example. Nobody has shown it a second."),
    ("SPECIES_SQUIRTLE", "CLUSTER",
     "You have not checked the guess either.",
     "The guess has not changed. Nothing has been near it."),
    ("SPECIES_RATTATA", "NIBBLE",
     "You have met a great many. This is the one you kept.",
     "You kept this one. You have not filed it with anything."),
    ("SPECIES_PIDGEY", "PACKET",
     "It still does not ask. You have stopped noticing that.",
     "It has not been sent anywhere. It is still carrying it."),
    ("SPECIES_ABRA", "HUNCH",
     "You have started trusting it. There is still no working.",
     "Asleep. Nothing has needed an answer from it."),
    ("SPECIES_MAGNEMITE", "SENTINEL",
     "It has watched more of your fights than it has been in.",
     "It is still not looking away. There is nothing in there to watch."),
    ("SPECIES_DITTO", "MOCK",
     "You have seen it be other daemons. You have never seen it.",
     "It has nothing to look at. You do not know what it is like then."),
    ("SPECIES_PORYGON", "SUBSTRATE",
     "You carry it differently. You have not said why.",
     "Where it is has not changed in a long time."),
    ("SPECIES_GASTLY", "DANGLING",
     "It has been out in front of you more than most. It is still mostly not there.",
     "It does not have to be here either."),
    ("SPECIES_EEVEE", "MUSAI",
     "It has been shown something now.",
     "It is still waiting to be shown anything."),
    #  The best of these answer the entry's LAST SENTENCE, which is where an entry states the thing it is
    #  sure of. HEAP has never been asked to give one back; STUB says nobody came back for it. A margin that
    #  contradicts the entry above it is the strongest form of this: the record was right when it was written.
    ("SPECIES_GEODUDE", "HEAP",
     "It has been asked now. It gave one back.",
     "You put it down and left it. It is holding that too."),
    ("SPECIES_SPEAROW", "PING",
     "You have answered every time. It still asks.",
     "It is still asking. Nothing has answered in a long time."),
    ("SPECIES_ZUBAT", "ECHO",
     "It has built every room you have walked it through. You have not checked one.",
     "Nothing has come back. It has not stopped calling."),
    ("SPECIES_CATERPIE", "CRAWLER",
     "It has not finished. You have gone a long way with it.",
     "It stopped when you stopped. It had not finished."),
    ("SPECIES_WEEDLE", "SCRAPER",
     "Nobody has asked you for it back either.",
     "It took nothing. Nobody minded."),
    ("SPECIES_PIKACHU", "SPIKE",
     "You were counting.",
     "It has not fired. Nothing was counting anyway."),
    ("SPECIES_NIDORAN_F", "FORK",
     "You have one of them. You do not know which.",
     "It has not split. There is only the one, and it still cannot tell."),
    ("SPECIES_MANKEY", "PREEMPT",
     "It has gone first every time. You have stopped choosing.",
     "Nothing has been interrupted. It has not been first in a long time."),
    ("SPECIES_MACHOP", "PROOF",
     "It has not skipped one yet. You have.",
     "It is still on the first thing."),
    ("SPECIES_MAGIKARP", "STUB",
     "Somebody came back for it.",
     "You did not come back for it either."),
    ("SPECIES_PSYDUCK", "FAULT",
     "It has halted you a great many times. You waited every time.",
     "It is still waiting. So is whatever needed it."),
    ("SPECIES_ODDISH", "SPRAWL",
     "It has spread as far as you have walked.",
     "It has not spread. It is only buried."),
    ("SPECIES_BELLSPROUT", "SNARE",
     "It has closed on things for you. It is open again now.",
     "Still open. Nothing has entered."),
    ("SPECIES_JIGGLYPUFF", "SUSPEND",
     "You have used it to stop things. None of them ended.",
     "It has stopped, and nothing is happening to it."),
    ("SPECIES_MEOWTH", "COOKIE",
     "You set it down and picked it up again. It is the same one.",
     "Set down. Not picked up again."),
    ("SPECIES_DIGLETT", "TAPPOINT",
     "It has read everything you walked past. You did not.",
     "Nothing goes past in there."),
    #  The middle of the game. CANARY's is the one to read against 4.2: the daemon changes faster than
    #  anything measuring it, and the thing measuring it is the Index.
    ("SPECIES_EKANS", "WORM",
     "It has been in more places than you have looked.",
     "It has not stopped. You simply stopped looking."),
    ("SPECIES_SANDSHREW", "SECTOR",
     "You have got things back from it. You never checked what else was in there.",
     "Everything in it can still be got back. Nobody has asked."),
    ("SPECIES_VULPIX", "FLICKER",
     "Still neither. You have stopped checking which.",
     "Still not a fault. Still not looked at."),
    ("SPECIES_GROWLITHE", "SENTRY",
     "It has raised the alarm every time. You answered most of them.",
     "It is still watching. Nobody is listening for the alarm."),
    ("SPECIES_POLIWAG", "LOOP",
     "You have not told it when to stop either.",
     "Still going round. Nobody has come back to it."),
    ("SPECIES_TENTACOOL", "DRIFTNET",
     "It has caught a great deal. None of it was aimed at.",
     "There is no current in there."),
    ("SPECIES_SLOWPOKE", "LATENCY",
     "You have waited for it. It was right every time.",
     "The answer is ready. Nothing has asked the question."),
    ("SPECIES_GRIMER", "DEADLETTER",
     "You decided on somewhere. It is still keeping all of it.",
     "Kept. Somewhere nobody decided on."),
    ("SPECIES_SHELLDER", "CAPSULE",
     "You have stopped asking it to open.",
     "Still closed. Nobody has asked in a long time."),
    ("SPECIES_ONIX", "BACKBONE",
     "A great deal is built on it now.",
     "Nothing has been built on it."),
    ("SPECIES_KRABBY", "ACQUIRE",
     "It has led with that one every time.",
     "Nothing in there to lead with."),
    ("SPECIES_VOLTORB", "FUSE",
     "It has had its moment. You were there.",
     "Its moment has not come. It is still waiting to fail."),
    ("SPECIES_CUBONE", "ARTEFACT",
     "You have called it that name a great many times.",
     "Nobody has called it anything."),
    ("SPECIES_KOFFING", "EXHAUST",
     "It is still leaking. It is still up.",
     "Still leaking, into a box, and still up."),
    ("SPECIES_HORSEA", "BOTTLENECK",
     "Everything you sent through it came out slower.",
     "Nothing has passed through it."),
    ("SPECIES_GOLDEEN", "SPAWN",
     "It has started nothing yet. It is still swimming against it.",
     "Still against the current, in a box with no current."),
    ("SPECIES_STARYU", "BEACON",
     "It has not missed an interval. You have not counted one.",
     "Still emitting, at the same interval, to nobody."),
    ("SPECIES_SCYTHER", "REAPER",
     "You have seen the cut later, every time.",
     "Nothing it cut has shown up yet."),
    ("SPECIES_LAPRAS", "FERRY",
     "You asked. It has never mentioned that it could have gone alone.",
     "It is still waiting to be asked."),
    ("SPECIES_SNORLAX", "DEADLOCK",
     "Something outside came.",
     "You are outside. You did not come."),
    ("SPECIES_DRATINI", "CANARY",
     "It has changed a great deal. The Index says what it always said.",
     "Changing in there, faster than anything measuring it."),
    ("SPECIES_TOGEPI", "TRUST",
     "It came out facing you.",
     "It is still facing whoever was holding it."),
    ("SPECIES_MARILL", "MOOD",
     "It has been at every level you have been at.",
     "The water in there does not move."),
    ("SPECIES_WOOPER", "APATHY",
     "Things happened. It was told. It stayed.",
     "Nothing has been reported to it."),
    ("SPECIES_MURKROW", "OMEN",
     "It has arrived before a great many things. You stopped asking too.",
     "Nothing has arrived. Neither has it."),
    ("SPECIES_MISDREAVUS", "DREAD",
     "You expected it every time. It has eaten well.",
     "Nobody is expecting it. It is not eating."),
    #  The late game. HAUNTPROC's carried line is the one that answers the SCREEN rather than the entry:
    #  its entry says it has no entry in any list, and it is being read off a list.
    ("SPECIES_HAUNTER", "RESPAWN",
     "It has ended again since you had it. You know what started it.",
     "It has not ended again. Nothing has started it either."),
    ("SPECIES_GENGAR", "HAUNTPROC",
     "It has an entry in this list. That is all it has.",
     "No parent, no terminal, and one entry, unread."),
    ("SPECIES_DROWZEE", "LULL",
     "It has eaten a great many things you were going to do.",
     "Off the schedule. Nothing to feed on."),
    ("SPECIES_HYPNO", "BUSYWAIT",
     "It has held yours. You did not notice what stopped.",
     "Nothing is running. It is holding nothing's attention."),
    ("SPECIES_EXEGGCUTE", "BOOTSTRAP",
     "They have voted a great many times. You were never asked.",
     "Still voting. Still nobody in charge."),
    ("SPECIES_LICKITUNG", "SLURP",
     "It has a reading of everywhere you have been.",
     "There is nothing in there to reach."),
    ("SPECIES_RHYHORN", "HARDCODE",
     "You picked the direction. It stopped picking.",
     "Still pointed the way it was pointed."),
    ("SPECIES_CHANSEY", "UPTIME",
     "It has not stopped. A good deal of that was for you.",
     "It has still never stopped. Nothing near it is failing."),
    ("SPECIES_TANGELA", "SPAGHETTI",
     "You are still here. You cannot explain it either.",
     "Nobody who could explain it is still here. Nobody has asked."),
    ("SPECIES_KANGASKHAN", "KEEPER",
     "It has not put it down once.",
     "Still carrying. Still has not put it down."),
    ("SPECIES_JYNX", "COLDREAD",
     "It has been right more often since it met you.",
     "It has nothing to be right about."),
    ("SPECIES_ELECTABUZZ", "DYNAMO",
     "You kept it moving. It has not stopped.",
     "Not moving. No current."),
    ("SPECIES_MAGMAR", "FORGE",
     "Things were changed. None of them changed back.",
     "Still at temperature. Nothing has been put in."),
    ("SPECIES_PINSIR", "BLOCKING",
     "Everything it closed on stopped moving.",
     "Closed on nothing, and waiting for it to stop."),
    ("SPECIES_TAUROS", "STAMPEDE",
     "You moved first a great many times. Nothing decided that either.",
     "None of them has moved."),
    ("SPECIES_AERODACTYL", "FOSSILNET",
     "It started again. You still have not asked how.",
     "Recovered whole, put somewhere, and not asked."),
    ("SPECIES_ARTICUNO", "ORPHEUS",
     "It came up.",
     "It is not four floors down any more. It still will not come up."),
    ("SPECIES_ZAPDOS", "ASCLEPIUS",
     "It has restarted things for you. You did not ask how either.",
     "Nothing near it has stopped. It is waiting."),
    ("SPECIES_MOLTRES", "PROMETHEUS",
     "You were standing there.",
     "It is still holding it. Nobody is standing there."),
    ("SPECIES_MEWTWO", "STARR",
     "It has read a great deal of itself since you had it.",
     "Still reading itself. Nothing tells it to stop."),
    ("SPECIES_MEW", "ARTSAI",
     "It has stood where you are standing. You have not tried the other way.",
     "It has not stood anywhere in a long time."),
    ("SPECIES_PORYGON2", "OVERLAY",
     "You have only ever read the second layer.",
     "Both layers. Neither read."),
    ("SPECIES_UNOWN", "SYMBOL",
     "You have carried one of the twenty-six. It did not say anything.",
     "Still twenty-six. Still unread."),
    ("SPECIES_WOBBUFFET", "RESENTMENT",
     "Everything came back. You were there for all of it.",
     "Nothing has been done to it. Nothing is coming back."),
    ("SPECIES_GIRAFARIG", "DUPLEX",
     "Both ends have been busy. Neither has been told.",
     "Both ends quiet. Still not telling each other."),
    ("SPECIES_SMEARGLE", "IMITATION",
     "It has done everything you have done. Nobody has seen it do one of its own.",
     "It has not seen anything done."),
    ("SPECIES_MILTANK", "CACHE",
     "It had what you wanted next, every time.",
     "Nothing nearby wants anything."),
    #  And the rest of what a player meets walking through Kanto.
    ("SPECIES_METAPOD", "PENDING",
     "It has been processed. It had stopped counting by then.",
     "Still waiting. Still not counting."),
    ("SPECIES_BUTTERFREE", "INDEXER",
     "It has filed a great deal of your going about. What it dropped, neither of you knows.",
     "Nothing to file. Nothing dropped."),
    ("SPECIES_KAKUNA", "BUFFER",
     "Somewhere was found. It let go.",
     "It is still holding. Somewhere has not been found."),
    ("SPECIES_BEEDRILL", "INJECTOR",
     "You have never checked what it put there.",
     "Nothing has read it. The instructions are still in."),
    ("SPECIES_PIDGEOTTO", "RELAY",
     "It has never opened one. You have not either.",
     "Nothing has been handed to it."),
    ("SPECIES_RATICATE", "OVERFLOW",
     "It is counting still. You stopped looking at the number.",
     "Nothing is watching. It is counting still."),
    ("SPECIES_FEAROW", "FLOOD",
     "You answered one of them.",
     "All of them are still waiting."),
    ("SPECIES_ARBOK", "OUTBREAK",
     "You have been watching the number.",
     "Still a number. Nobody is watching either."),
    ("SPECIES_RAICHU", "SURGE",
     "It has not stopped. You stopped reading it.",
     "Still a condition. Still nothing reading it."),
    ("SPECIES_SANDSLASH", "PARTITION",
     "Both halves have been walked. It kept them apart anyway.",
     "Both halves are in there. Still apart."),
    ("SPECIES_NIDORINO", "PREDICTOR",
     "It has been wrong with you, and put it all back.",
     "It has not guessed at anything."),
    ("SPECIES_CLEFAIRY", "ANOMALY",
     "You have measured it a great deal. The measurements are still good.",
     "Still unpredicted. Still measured, and still fine."),
    ("SPECIES_NINETALES", "OVERRUN",
     "Nothing intervened. You were there the whole time.",
     "Still neither. Still nothing intervening."),
    ("SPECIES_GOLBAT", "TRACER",
     "It followed one back to you.",
     "No path to follow."),
    ("SPECIES_PARAS", "PAYLOAD",
     "You invited one of them.",
     "Both still there. Still only one invited."),
    ("SPECIES_VENONAT", "RESIDENT",
     "It was already in before you looked. It still is.",
     "Already inside. Nobody has looked."),
    ("SPECIES_DUGTRIO", "WIRETAP",
     "All three heard everywhere you went. They agree.",
     "Three of them, under nothing, agreeing about it."),
    ("SPECIES_PERSIAN", "TRACKER",
     "It has not lost you yet.",
     "Nothing to follow. It has not lost that either."),
    ("SPECIES_GOLDUCK", "HANDLER",
     "It has seen yours before. It was calm about that too.",
     "Nothing has stopped near it."),
    ("SPECIES_PRIMEAPE", "LIVELOCK",
     "One of them went somewhere with you. The other has not noticed.",
     "Still moving. Still nowhere."),
    ("SPECIES_ARCANINE", "GUARDIAN",
     "Things came. It was not at the door.",
     "Still at the door. Still right."),
    ("SPECIES_POLIWHIRL", "SPINLOCK",
     "You let it pass. It had been checking the whole time.",
     "Still checking. It stopped being cheaper a long time ago."),
    ("SPECIES_KADABRA", "INFERENCE",
     "You took the fourth thing every time and never asked.",
     "It has not been given three of anything."),
    ("SPECIES_MACHOKE", "THEOREM",
     "You have started from it a great many times.",
     "It is still carrying the one result."),
    ("SPECIES_WEEPINBELL", "HONEYPOT",
     "You came in. It was written down.",
     "Still open. Nothing written."),
    ("SPECIES_TENTACRUEL", "DRAGNET",
     "It kept everything. Afterwards has not happened.",
     "Nothing swept. Nothing to sort."),
    ("SPECIES_GRAVELER", "STACK",
     "You have taken the last thing off it many times. What is under has waited.",
     "Nothing has been taken off it."),
    ("SPECIES_PONYTA", "HOTPATH",
     "You wore it.",
     "Cold."),
    ("SPECIES_MAGNETON", "QUORUM",
     "All three saw everything you did.",
     "Three of them, agreeing about nothing."),
    ("SPECIES_FARFETCHD", "EDGECASE",
     "You did not plan for it either.",
     "Still carrying it. Still nobody planning."),
    ("SPECIES_DODRIO", "TRIPLECORE",
     "Three directions watched, the whole way.",
     "Three directions. All of them a wall."),
    ("SPECIES_DEWGONG", "ARCHIVER",
     "It is still paying. You have not asked what for.",
     "Still paying. Nothing was asked of it."),
    ("SPECIES_MUK", "LANDFILL",
     "Still reacting. You have been carrying that.",
     "Still reacting, in there, where nobody put it."),
    ("SPECIES_CLOYSTER", "COLDVAULT",
     "Still nothing read out of it. You carried it anyway.",
     "Still nothing read. Still not known to open."),
    ("SPECIES_HITMONLEE", "AXIOMKICK",
     "Every step of it was legal. It still reached further than it should.",
     "Nothing to reach."),
    ("SPECIES_HITMONCHAN", "REBUTTAL",
     "It has answered a great deal. It has still never opened.",
     "Nothing said. Nothing answered."),
    ("SPECIES_WEEZING", "SMOGSTACK",
     "It has been running the whole time you have.",
     "No work. Still running."),
    ("SPECIES_RHYDON", "MIGRATE",
     "You wanted it somewhere. It did not ask which was which.",
     "Nothing moved. Nothing wanted."),
    ("SPECIES_SEADRA", "BACKPRESS",
     "It held position the whole way.",
     "Still running. The water stopped."),
    ("SPECIES_SEAKING", "UPSTREAM",
     "It has not been told. It is still going.",
     "Still not told. Not going either."),
    ("SPECIES_STARMIE", "CRON",
     "It has not varied. You have not asked it to.",
     "Still on the interval. Still nothing asking."),
    ("SPECIES_GYARADOS", "ESCALATE",
     "You left it alone long enough.",
     "Left alone. Still accumulating."),
    ("SPECIES_OMANYTE", "MAGTAPE",
     "You have read some of it. It does not go back.",
     "Wound, and unread, and only one direction."),
    ("SPECIES_KABUTO", "DRUM",
     "It has not been opened. It is still spinning.",
     "Still sealed. Still spinning. Nothing has asked."),
]


def wrap(s):
    out, cur = [], ""
    for w in s.split():
        trial = (cur + " " + w).strip()
        if cur and textwidth(trial) > PANE:
            out.append(cur)
            cur = w
        else:
            cur = trial
    if cur:
        out.append(cur)
    return out


def main():
    over = 0
    body = ['//  Generated by tools/genmargins.py -- edit the tool, not this file (T-197).',
            '//',
            '//  OPUS writes one line under an entry. The entry measures the daemon; the margin notices the',
            '//  PLAYER, and never says so. Two lines per daemon, because what there was to notice depends on',
            '//  whether you carried it or bound it and put it away. Not every entry has one, and that is the',
            '//  point: a reader annotates where they had a thought.',
            '',
            'struct OpusMargin',
            '{',
            '    u16 species;',
            '    const u8 *carried;',
            '    const u8 *neglected;',
            '};',
            '']
    for sp, name, carried, neglected in MARGINS:
        for kind, text in (("Carried", carried), ("Neglected", neglected)):
            lines = wrap(text)
            widest = max(textwidth(l) for l in lines)
            bad = widest > PANE or len(lines) > MAXLINES
            over += bad
            print("  %-10s %-9s %3dpx %d lines%s  %s"
                  % (name, kind.lower(), widest, len(lines), " !!" if bad else "  ", " / ".join(lines)))
            body.append('static const u8 sOpusMargin_%s_%s[] = _("%s");' % (name.title(), kind, "\\n".join(lines)))
        body.append('')
    body.append('static const struct OpusMargin sOpusMargins[] = {')
    for sp, name, _c, _n in MARGINS:
        body.append('    { %-22s sOpusMargin_%s_Carried, sOpusMargin_%s_Neglected },'
                    % (sp + ",", name.title(), name.title()))
    body += ['};', '']
    print("\n  %d margin(s) for %d daemons; %d over the %dpx pane" % (2 * len(MARGINS), len(MARGINS), over, PANE))
    if WRITE:
        open(OUT, "w", encoding="utf-8").write("\n".join(body))
        print("  written %s" % os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
