#!/usr/bin/env python3
"""OPUS's margin lines, wrapped to the Index entry's own pane (T-197; vision.md 4.2).

    python3 tools/genmargins.py            # report every line, measured
    python3 tools/genmargins.py --write     # write src/data/opus_margins.h

WHAT A MARGIN LINE IS. The entry measures the daemon -- height, weight, type, stats, and the thin sentence
4.2 is about. The margin notices the PLAYER, and never says so. It is never a measurement, never advice,
never a hint, and it only makes sense read against the entry above it.

TWO LINES, because what OPUS noticed depends on what you did. A daemon you levelled gets one line; a daemon
you bound and put away gets another. The second is not a scold -- it is the same quiet noticing, aimed at the
thing you did not do.

NOT EVERY ENTRY HAS ONE, and that is the point: a reader annotates where they had a thought.

THE PANE is the entry's own, demonstrated rather than declared -- 234px and four lines, which is the widest
line and the most lines the 386 entries use.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GBA = os.path.join(ROOT, "engineGba")
OUT = os.path.join(GBA, "src/data/opus_margins.h")
PANE, MAXLINES = 234, 4
WRITE = "--write" in sys.argv

_src = open(os.path.join(ROOT, "tools/port_vocab.py"), encoding="utf-8").read()
_ns = {"__name__": "port_vocab_font", "__file__": os.path.join(ROOT, "tools/port_vocab.py")}
exec(compile(_src.split("# ------------------------------------------------------- names, derived")[0],
             "port_vocab.py", "exec"), _ns)
textwidth = _ns["textwidth"]

#  (species constant, our name, carried, neglected)
MARGINS = [
    ("SPECIES_BULBASAUR", "ROVERCUB",
     "It remembers the way back to the first town. You have not gone that way in some time.",
     "It is not being carried past anything."),
    ("SPECIES_CHARMANDER", "LABEL",
     "It has met you now. It has not changed the answer.",
     "It is still holding the one example. Nobody has shown it a second."),
    ("SPECIES_SQUIRTLE", "CLUSTER",
     "You have not checked the guess either.",
     "The guess has not changed. Nothing has been near it."),
    ("SPECIES_RATTATA", "NIBBLE",
     "You have met a great many. This is the one you kept.",
     "You kept this one. You have not filed it with anything."),
    ("SPECIES_PIDGEY", "PACKET",
     "It still does not ask. You have stopped noticing that.",
     "It has not been sent anywhere. It is still carrying it."),
    ("SPECIES_ABRA", "HUNCH",
     "You have started trusting it. There is still no working.",
     "Asleep. Nothing has needed an answer from it."),
    ("SPECIES_MAGNEMITE", "SENTINEL",
     "It has watched more of your fights than it has been in.",
     "It is still not looking away. There is nothing in there to watch."),
    ("SPECIES_DITTO", "MOCK",
     "You have seen it be other daemons. You have never seen it.",
     "It has nothing to look at. You do not know what it is like then."),
    ("SPECIES_PORYGON", "SUBSTRATE",
     "You carry it differently. You have not said why.",
     "Where it is has not changed in a long time."),
    ("SPECIES_GASTLY", "DANGLING",
     "It has been out in front of you more than most. It is still mostly not there.",
     "It does not have to be here either."),
    ("SPECIES_EEVEE", "MUSAI",
     "It has been shown something now.",
     "It is still waiting to be shown anything."),
    #  The best of these answer the entry's LAST SENTENCE, which is where an entry states the thing it is
    #  sure of. HEAP has never been asked to give one back; STUB says nobody came back for it. A margin that
    #  contradicts the entry above it is the strongest form of this: the record was right when it was written.
    ("SPECIES_GEODUDE", "HEAP",
     "It has been asked now. It gave one back.",
     "You put it down and left it. It is holding that too."),
    ("SPECIES_SPEAROW", "PING",
     "You have answered every time. It still asks.",
     "It is still asking. Nothing has answered in a long time."),
    ("SPECIES_ZUBAT", "ECHO",
     "It has built every room you have walked it through. You have not checked one.",
     "Nothing has come back. It has not stopped calling."),
    ("SPECIES_CATERPIE", "CRAWLER",
     "It has not finished. You have gone a long way with it.",
     "It stopped when you stopped. It had not finished."),
    ("SPECIES_WEEDLE", "SCRAPER",
     "Nobody has asked you for it back either.",
     "It took nothing. Nobody minded."),
    ("SPECIES_PIKACHU", "SPIKE",
     "You were counting.",
     "It has not fired. Nothing was counting anyway."),
    ("SPECIES_NIDORAN_F", "FORK",
     "You have one of them. You do not know which.",
     "It has not split. There is only the one, and it still cannot tell."),
    ("SPECIES_MANKEY", "PREEMPT",
     "It has gone first every time. You have stopped choosing.",
     "Nothing has been interrupted. It has not been first in a long time."),
    ("SPECIES_MACHOP", "PROOF",
     "It has not skipped one yet. You have.",
     "It is still on the first thing."),
    ("SPECIES_MAGIKARP", "STUB",
     "Somebody came back for it.",
     "You did not come back for it either."),
    ("SPECIES_PSYDUCK", "FAULT",
     "It has halted you a great many times. You waited every time.",
     "It is still waiting. So is whatever needed it."),
    ("SPECIES_ODDISH", "SPRAWL",
     "It has spread as far as you have walked.",
     "It has not spread. It is only buried."),
    ("SPECIES_BELLSPROUT", "SNARE",
     "It has closed on things for you. It is open again now.",
     "Still open. Nothing has entered."),
    ("SPECIES_JIGGLYPUFF", "SUSPEND",
     "You have used it to stop things. None of them ended.",
     "It has stopped, and nothing is happening to it."),
    ("SPECIES_MEOWTH", "COOKIE",
     "You set it down and picked it up again. It is the same one.",
     "Set down. Not picked up again."),
    ("SPECIES_DIGLETT", "TAPPOINT",
     "It has read everything you walked past. You did not.",
     "Nothing goes past in there."),
    #  The middle of the game. CANARY's is the one to read against 4.2: the daemon changes faster than
    #  anything measuring it, and the thing measuring it is the Index.
    ("SPECIES_EKANS", "WORM",
     "It has been in more places than you have looked.",
     "It has not stopped. You simply stopped looking."),
    ("SPECIES_SANDSHREW", "SECTOR",
     "You have got things back from it. You never checked what else was in there.",
     "Everything in it can still be got back. Nobody has asked."),
    ("SPECIES_VULPIX", "FLICKER",
     "Still neither. You have stopped checking which.",
     "Still not a fault. Still not looked at."),
    ("SPECIES_GROWLITHE", "SENTRY",
     "It has raised the alarm every time. You answered most of them.",
     "It is still watching. Nobody is listening for the alarm."),
    ("SPECIES_POLIWAG", "LOOP",
     "You have not told it when to stop either.",
     "Still going round. Nobody has come back to it."),
    #  NOT "caught": 1.1 renamed the capture verb, so port_vocab reads it as bind and writes "It has bound a
    #  great deal" -- which is what a PLAYER does to a daemon, not what a net does to what drifts into it.
    #  The word goes rather than the rule.
    ("SPECIES_TENTACOOL", "DRIFTNET",
     "It has taken a great deal. None of it was aimed at.",
     "There is no current in there."),
    ("SPECIES_SLOWPOKE", "LATENCY",
     "You have waited for it. It was right every time.",
     "The answer is ready. Nothing has asked the question."),
    ("SPECIES_GRIMER", "DEADLETTER",
     "You decided on somewhere. It is still keeping all of it.",
     "Kept. Somewhere nobody decided on."),
    ("SPECIES_SHELLDER", "CAPSULE",
     "You have stopped asking it to open.",
     "Still closed. Nobody has asked in a long time."),
    ("SPECIES_ONIX", "BACKBONE",
     "A great deal is built on it now.",
     "Nothing has been built on it."),
    ("SPECIES_KRABBY", "ACQUIRE",
     "It has led with that one every time.",
     "Nothing in there to lead with."),
    ("SPECIES_VOLTORB", "FUSE",
     "It has had its moment. You were there.",
     "Its moment has not come. It is still waiting to fail."),
    ("SPECIES_CUBONE", "ARTEFACT",
     "You have called it that name a great many times.",
     "Nobody has called it anything."),
    ("SPECIES_KOFFING", "EXHAUST",
     "It is still leaking. It is still up.",
     "Still leaking, into a box, and still up."),
    ("SPECIES_HORSEA", "BOTTLENECK",
     "Everything you sent through it came out slower.",
     "Nothing has passed through it."),
    ("SPECIES_GOLDEEN", "SPAWN",
     "It has started nothing yet. It is still swimming against it.",
     "Still against the current, in a box with no current."),
    ("SPECIES_STARYU", "BEACON",
     "It has not missed an interval. You have not counted one.",
     "Still emitting, at the same interval, to nobody."),
    ("SPECIES_SCYTHER", "REAPER",
     "You have seen the cut later, every time.",
     "Nothing it cut has shown up yet."),
    ("SPECIES_LAPRAS", "FERRY",
     "You asked. It has never mentioned that it could have gone alone.",
     "It is still waiting to be asked."),
    ("SPECIES_SNORLAX", "DEADLOCK",
     "Something outside came.",
     "You are outside. You did not come."),
    ("SPECIES_DRATINI", "CANARY",
     "It has changed a great deal. The Index says what it always said.",
     "Changing in there, faster than anything measuring it."),
    ("SPECIES_TOGEPI", "TRUST",
     "It came out facing you.",
     "It is still facing whoever was holding it."),
    ("SPECIES_MARILL", "MOOD",
     "It has been at every level you have been at.",
     "The water in there does not move."),
    ("SPECIES_WOOPER", "APATHY",
     "Things happened. It was told. It stayed.",
     "Nothing has been reported to it."),
    ("SPECIES_MURKROW", "OMEN",
     "It has arrived before a great many things. You stopped asking too.",
     "Nothing has arrived. Neither has it."),
    ("SPECIES_MISDREAVUS", "DREAD",
     "You expected it every time. It has eaten well.",
     "Nobody is expecting it. It is not eating."),
    #  The late game. HAUNTPROC's carried line is the one that answers the SCREEN rather than the entry:
    #  its entry says it has no entry in any list, and it is being read off a list.
    ("SPECIES_HAUNTER", "RESPAWN",
     "It has ended again since you had it. You know what started it.",
     "It has not ended again. Nothing has started it either."),
    ("SPECIES_GENGAR", "HAUNTPROC",
     "It has an entry in this list. That is all it has.",
     "No parent, no terminal, and one entry, unread."),
    ("SPECIES_DROWZEE", "LULL",
     "It has eaten a great many things you were going to do.",
     "Off the schedule. Nothing to feed on."),
    ("SPECIES_HYPNO", "BUSYWAIT",
     "It has held yours. You did not notice what stopped.",
     "Nothing is running. It is holding nothing's attention."),
    ("SPECIES_EXEGGCUTE", "BOOTSTRAP",
     "They have voted a great many times. You were never asked.",
     "Still voting. Still nobody in charge."),
    ("SPECIES_LICKITUNG", "SLURP",
     "It has a reading of everywhere you have been.",
     "There is nothing in there to reach."),
    ("SPECIES_RHYHORN", "HARDCODE",
     "You picked the direction. It stopped picking.",
     "Still pointed the way it was pointed."),
    ("SPECIES_CHANSEY", "UPTIME",
     "It has not stopped. A good deal of that was for you.",
     "It has still never stopped. Nothing near it is failing."),
    ("SPECIES_TANGELA", "SPAGHETTI",
     "You are still here. You cannot explain it either.",
     "Nobody who could explain it is still here. Nobody has asked."),
    ("SPECIES_KANGASKHAN", "KEEPER",
     "It has not put it down once.",
     "Still carrying. Still has not put it down."),
    ("SPECIES_JYNX", "COLDREAD",
     "It has been right more often since it met you.",
     "It has nothing to be right about."),
    ("SPECIES_ELECTABUZZ", "DYNAMO",
     "You kept it moving. It has not stopped.",
     "Not moving. No current."),
    ("SPECIES_MAGMAR", "FORGE",
     "Things were changed. None of them changed back.",
     "Still at temperature. Nothing has been put in."),
    ("SPECIES_PINSIR", "BLOCKING",
     "Everything it closed on stopped moving.",
     "Closed on nothing, and waiting for it to stop."),
    ("SPECIES_TAUROS", "STAMPEDE",
     "You moved first a great many times. Nothing decided that either.",
     "None of them has moved."),
    ("SPECIES_AERODACTYL", "FOSSILNET",
     "It started again. You still have not asked how.",
     "Recovered whole, put somewhere, and not asked."),
    ("SPECIES_ARTICUNO", "ORPHEUS",
     "It came up.",
     "It is not four floors down any more. It still will not come up."),
    ("SPECIES_ZAPDOS", "ASCLEPIUS",
     "It has restarted things for you. You did not ask how either.",
     "Nothing near it has stopped. It is waiting."),
    ("SPECIES_MOLTRES", "PROMETHEUS",
     "You were standing there.",
     "It is still holding it. Nobody is standing there."),
    ("SPECIES_MEWTWO", "STARR",
     "It has read a great deal of itself since you had it.",
     "Still reading itself. Nothing tells it to stop."),
    ("SPECIES_MEW", "ARTSAI",
     "It has stood where you are standing. You have not tried the other way.",
     "It has not stood anywhere in a long time."),
    ("SPECIES_PORYGON2", "OVERLAY",
     "You have only ever read the second layer.",
     "Both layers. Neither read."),
    ("SPECIES_UNOWN", "SYMBOL",
     "You have carried one of the twenty-six. It did not say anything.",
     "Still twenty-six. Still unread."),
    ("SPECIES_WOBBUFFET", "RESENTMENT",
     "Everything came back. You were there for all of it.",
     "Nothing has been done to it. Nothing is coming back."),
    ("SPECIES_GIRAFARIG", "DUPLEX",
     "Both ends have been busy. Neither has been told.",
     "Both ends quiet. Still not telling each other."),
    ("SPECIES_SMEARGLE", "IMITATION",
     "It has done everything you have done. Nobody has seen it do one of its own.",
     "It has not seen anything done."),
    ("SPECIES_MILTANK", "CACHE",
     "It had what you wanted next, every time.",
     "Nothing nearby wants anything."),
    #  And the rest of what a player meets walking through Kanto.
    ("SPECIES_METAPOD", "PENDING",
     "It has been processed. It had stopped counting by then.",
     "Still waiting. Still not counting."),
    ("SPECIES_BUTTERFREE", "INDEXER",
     "It has filed a great deal of your going about. What it dropped, neither of you knows.",
     "Nothing to file. Nothing dropped."),
    ("SPECIES_KAKUNA", "BUFFER",
     "Somewhere was found. It let go.",
     "It is still holding. Somewhere has not been found."),
    ("SPECIES_BEEDRILL", "INJECTOR",
     "You have never checked what it put there.",
     "Nothing has read it. The instructions are still in."),
    ("SPECIES_PIDGEOTTO", "RELAY",
     "It has never opened one. You have not either.",
     "Nothing has been handed to it."),
    ("SPECIES_RATICATE", "OVERFLOW",
     "It is counting still. You stopped looking at the number.",
     "Nothing is watching. It is counting still."),
    ("SPECIES_FEAROW", "FLOOD",
     "You answered one of them.",
     "All of them are still waiting."),
    ("SPECIES_ARBOK", "OUTBREAK",
     "You have been watching the number.",
     "Still a number. Nobody is watching either."),
    ("SPECIES_RAICHU", "SURGE",
     "It has not stopped. You stopped reading it.",
     "Still a condition. Still nothing reading it."),
    ("SPECIES_SANDSLASH", "PARTITION",
     "Both halves have been walked. It kept them apart anyway.",
     "Both halves are in there. Still apart."),
    ("SPECIES_NIDORINO", "PREDICTOR",
     "It has been wrong with you, and put it all back.",
     "It has not guessed at anything."),
    ("SPECIES_CLEFAIRY", "ANOMALY",
     "You have measured it a great deal. The measurements are still good.",
     "Still unpredicted. Still measured, and still fine."),
    ("SPECIES_NINETALES", "OVERRUN",
     "Nothing intervened. You were there the whole time.",
     "Still neither. Still nothing intervening."),
    ("SPECIES_GOLBAT", "TRACER",
     "It followed one back to you.",
     "No path to follow."),
    ("SPECIES_PARAS", "PAYLOAD",
     "You invited one of them.",
     "Both still there. Still only one invited."),
    ("SPECIES_VENONAT", "RESIDENT",
     "It was already in before you looked. It still is.",
     "Already inside. Nobody has looked."),
    ("SPECIES_DUGTRIO", "WIRETAP",
     "All three heard everywhere you went. They agree.",
     "Three of them, under nothing, agreeing about it."),
    ("SPECIES_PERSIAN", "TRACKER",
     "It has not lost you yet.",
     "Nothing to follow. It has not lost that either."),
    ("SPECIES_GOLDUCK", "HANDLER",
     "It has seen yours before. It was calm about that too.",
     "Nothing has stopped near it."),
    ("SPECIES_PRIMEAPE", "LIVELOCK",
     "One of them went somewhere with you. The other has not noticed.",
     "Still moving. Still nowhere."),
    ("SPECIES_ARCANINE", "GUARDIAN",
     "Things came. It was not at the door.",
     "Still at the door. Still right."),
    ("SPECIES_POLIWHIRL", "SPINLOCK",
     "You let it pass. It had been checking the whole time.",
     "Still checking. It stopped being cheaper a long time ago."),
    ("SPECIES_KADABRA", "INFERENCE",
     "You took the fourth thing every time and never asked.",
     "It has not been given three of anything."),
    ("SPECIES_MACHOKE", "THEOREM",
     "You have started from it a great many times.",
     "It is still carrying the one result."),
    ("SPECIES_WEEPINBELL", "HONEYPOT",
     "You came in. It was written down.",
     "Still open. Nothing written."),
    ("SPECIES_TENTACRUEL", "DRAGNET",
     "It kept everything. Afterwards has not happened.",
     "Nothing swept. Nothing to sort."),
    ("SPECIES_GRAVELER", "STACK",
     "You have taken the last thing off it many times. What is under has waited.",
     "Nothing has been taken off it."),
    ("SPECIES_PONYTA", "HOTPATH",
     "You wore it.",
     "Cold."),
    ("SPECIES_MAGNETON", "QUORUM",
     "All three saw everything you did.",
     "Three of them, agreeing about nothing."),
    ("SPECIES_FARFETCHD", "EDGECASE",
     "You did not plan for it either.",
     "Still carrying it. Still nobody planning."),
    ("SPECIES_DODRIO", "TRIPLECORE",
     "Three directions watched, the whole way.",
     "Three directions. All of them a wall."),
    ("SPECIES_DEWGONG", "ARCHIVER",
     "It is still paying. You have not asked what for.",
     "Still paying. Nothing was asked of it."),
    ("SPECIES_MUK", "LANDFILL",
     "Still reacting. You have been carrying that.",
     "Still reacting, in there, where nobody put it."),
    ("SPECIES_CLOYSTER", "COLDVAULT",
     "Still nothing read out of it. You carried it anyway.",
     "Still nothing read. Still not known to open."),
    ("SPECIES_HITMONLEE", "AXIOMKICK",
     "Every step of it was legal. It still reached further than it should.",
     "Nothing to reach."),
    ("SPECIES_HITMONCHAN", "REBUTTAL",
     "It has answered a great deal. It has still never opened.",
     "Nothing said. Nothing answered."),
    ("SPECIES_WEEZING", "SMOGSTACK",
     "It has been running the whole time you have.",
     "No work. Still running."),
    ("SPECIES_RHYDON", "MIGRATE",
     "You wanted it somewhere. It did not ask which was which.",
     "Nothing moved. Nothing wanted."),
    ("SPECIES_SEADRA", "BACKPRESS",
     "It held position the whole way.",
     "Still running. The water stopped."),
    ("SPECIES_SEAKING", "UPSTREAM",
     "It has not been told. It is still going.",
     "Still not told. Not going either."),
    ("SPECIES_STARMIE", "CRON",
     "It has not varied. You have not asked it to.",
     "Still on the interval. Still nothing asking."),
    ("SPECIES_GYARADOS", "ESCALATE",
     "You left it alone long enough.",
     "Left alone. Still accumulating."),
    ("SPECIES_OMANYTE", "MAGTAPE",
     "You have read some of it. It does not go back.",
     "Wound, and unread, and only one direction."),
    ("SPECIES_KABUTO", "DRUM",
     "It has not been opened. It is still spinning.",
     "Still sealed. Still spinning. Nothing has asked."),
    #  T-197a: the target is not 386 and never was -- it is every daemon a player can REACH, which
    #  tools/gbareach.py answers: 213. At 124 the coverage of those was 57%, which is a shortfall and not a
    #  stopping point. These are the rest of what someone can actually carry.
    ("SPECIES_AIPOM", "GRASP",
     "Everything you walked past was picked up and turned over.",
     "Nothing to pass. Nothing turned over."),
    ("SPECIES_ALAKAZAM", "CONJECTURE",
     "Still unproved. You have not tried either.",
     "The waiting has got longer."),
    ("SPECIES_BELLOSSOM", "GOLDSET",
     "You have used the answers. You did not check the hands.",
     "Still checked once. Still nobody checking the hands."),
    ("SPECIES_BLASTOISE", "MANIFOLD",
     "It showed you the shape. You called it something anyway.",
     "The shape is still there. Nobody has looked at it."),
    ("SPECIES_CHARIZARD", "CANON",
     "You were filed as an error once. The file is still not read.",
     "No new cases. Nothing to file."),
    ("SPECIES_CHARMELEON", "RUBRIC",
     "You did not check the rule either.",
     "Still applying it. To nothing."),
    ("SPECIES_CHINCHOU", "PILOT",
     "You took it into the dark. The line was live the whole time.",
     "Still lit. Nothing to show."),
    ("SPECIES_CLEFABLE", "OUTLIER",
     "You did not drop it.",
     "Dropped again."),
    ("SPECIES_CROBAT", "MULTICAST",
     "You never asked either.",
     "Four places, and it has been to none of them."),
    ("SPECIES_DELIBIRD", "REPAY",
     "The amounts still do not match. It is still coming.",
     "Nobody has fed it. It has nothing to bring."),
    ("SPECIES_DEOXYS", "PROTEUS",
     "You held on. The last one is the one you have.",
     "Still changing. Nobody is looking."),
    ("SPECIES_DODUO", "DUALCORE",
     "They agreed, eventually, every time.",
     "No task. They are still agreeing about it."),
    ("SPECIES_DRAGONAIR", "EMERGENCE",
     "Nothing was added. You were there for all of it.",
     "Nothing added. Nothing observed."),
    ("SPECIES_DRAGONITE", "SINGULAR",
     "It arrived reliably. You stopped being surprised.",
     "Reliable, and unobserved."),
    ("SPECIES_DUNSPARCE", "BLINDSPOT",
     "You saw one.",
     "You have one. You have not seen it."),
    ("SPECIES_ELECTRODE", "BREAKER",
     "It has not had to yet.",
     "Rated for nothing. Nothing coming."),
    ("SPECIES_EXEGGUTOR", "ENSEMBLE",
     "You have only ever heard the single answer.",
     "Several heads, and nothing to answer."),
    ("SPECIES_FLAAFFY", "BUILDUP",
     "You spent some of it. Everyone is still careful.",
     "Still going up. Nobody nearby."),
    ("SPECIES_FLAREON", "CODEMUSAI",
     "Every rule it met came from you. It did not ask.",
     "No rule. It has not stopped."),
    ("SPECIES_GLOOM", "SKEW",
     "Everything downwind of you grew differently.",
     "Still dripping. Nothing downwind."),
    ("SPECIES_GOLEM", "MONOLITH",
     "You took all of it, every time.",
     "Still one piece. Still efficient."),
    ("SPECIES_HERACROSS", "DRIVE",
     "The thing moved. It has not stopped.",
     "Nothing to push at. It has not stopped."),
    ("SPECIES_HITMONTOP", "CIRCULAR",
     "It finished a great many times. You went somewhere.",
     "Back where it started. Very fast."),
    ("SPECIES_HOOTHOOT", "POLL",
     "It has a great many answers about you. You have not read one.",
     "Still asking. The answer has not changed."),
    ("SPECIES_HOPPIP", "WHIM",
     "It went where you went. It says it chose.",
     "No air. It still says it chose."),
    ("SPECIES_HOUNDOOM", "OBSESSION",
     "You remember it.",
     "Still the one cry. Nobody has heard it."),
    ("SPECIES_HOUNDOUR", "FIXATION",
     "It picked you.",
     "It has not picked anything."),
    ("SPECIES_HO_OH", "PHOENIX",
     "It has started itself since you had it. You did nothing.",
     "It has not needed to start."),
    ("SPECIES_IVYSAUR", "ROVERSEER",
     "It has been outside. The answers are the same.",
     "Still inside. Still answering."),
    ("SPECIES_JOLTEON", "SEEKMUSAI",
     "You were shown the nearest match a great many times. Nobody told you either.",
     "Nothing shown. Nothing matched."),
    ("SPECIES_KABUTOPS", "PUNCHCARD",
     "A great deal was cut. None of it has been read back.",
     "Nothing cut. Nothing read."),
    ("SPECIES_KINGDRA", "TURBULENCE",
     "Nothing was wrong when it left you either.",
     "Nothing upstream. Nothing arriving."),
    ("SPECIES_KINGLER", "LOCKUP",
     "It closed on a great deal. It opened slowly each time.",
     "Closed. Nothing in it."),
    ("SPECIES_LANTURN", "SOUNDING",
     "It found the bottom every time. You did not ask how far.",
     "Still sending. Nothing coming back."),
    ("SPECIES_LARVITAR", "RUMINATE",
     "It is out. It is still eating.",
     "Still eating. Still in."),
    ("SPECIES_LEDYBA", "HUDDLE",
     "It was not alone.",
     "Alone."),
    ("SPECIES_LUGIA", "TRITON",
     "It has said nothing to you either.",
     "Nothing quarrelling. Nothing to settle."),
    ("SPECIES_MACHAMP", "LEMMA MIND",
     "It held all of it. You held one part.",
     "Still holding all of it."),
    ("SPECIES_MAGCARGO", "CALLOUS",
     "You touched the shell a great many times.",
     "Still molten. Nothing touching."),
    ("SPECIES_MANTINE", "BUOYANCY",
     "You put a great deal on it. It rose anyway.",
     "Nothing on it. Still rising."),
    ("SPECIES_MAREEP", "TENSION",
     "You found out how much.",
     "Still gathering. Nobody has touched it."),
    ("SPECIES_MAROWAK", "COREFILE",
     "It carried it everywhere you went. It has still not put it down.",
     "Still carrying it. Nowhere."),
    ("SPECIES_NATU", "VIGILANCE",
     "It still has not happened. It still has not looked away.",
     "Nothing to watch. It has not looked away."),
    ("SPECIES_NIDOKING", "PIPELINE",
     "You never interrupted it.",
     "Six things, all stopped, none finished."),
    ("SPECIES_NIDOQUEEN", "SCHEDULER",
     "You decided instead. It did not appeal either.",
     "Nothing to decide about. Still deciding."),
    ("SPECIES_NIDORAN_M", "BRANCH",
     "It picked early every time. You did not check the other way.",
     "No steps. Nothing to pick."),
    ("SPECIES_NIDORINA", "THREAD",
     "You changed one of them.",
     "Beside nothing. Sharing it with nobody."),
    ("SPECIES_NOCTOWL", "SUPERVISOR",
     "It started you again more than once.",
     "Nothing moving. Nothing to restart."),
    ("SPECIES_NUMEL", "PIXELBYTE",
     "It has drawn a great deal for you. It still cannot say what.",
     "Still static. Nothing taken away."),
    ("SPECIES_PARASECT", "ROOTKIT",
     "Nothing looked different to you either.",
     "Still running it. Still nothing looks different."),
    ("SPECIES_PHANPY", "RECALL",
     "It has a year of you, exactly.",
     "It is keeping everything. Nothing has happened."),
    ("SPECIES_PIDGEOT", "BROADCAST",
     "Some of it landed on you. It is still sending.",
     "Still sending. Nowhere is listening."),
    ("SPECIES_PILOSWINE", "IMPULSE",
     "It charged a great many times. It was usually right.",
     "Nothing to charge at. It still cannot see."),
    ("SPECIES_PINECO", "STARTLE",
     "You touched it once.",
     "Still hanging. Months."),
    ("SPECIES_POLIWRATH", "MUTEX",
     "You held it. You let go.",
     "Nobody is holding it. Everyone is waiting anyway."),
    ("SPECIES_QWILFISH", "BRISTLE",
     "It is still that size.",
     "Nothing has threatened it. It is still that size."),
    ("SPECIES_RAPIDASH", "OVERDRIVE",
     "You never made it check.",
     "Still not stopping. Not going anywhere."),
    ("SPECIES_REMORAID", "ATTACHMENT",
     "It fastened to you. It still did not choose.",
     "Nothing larger. Nowhere."),
    ("SPECIES_SEEL", "HEATSINK",
     "It took a great deal and did not warm.",
     "Nothing to draw. Still cold."),
    ("SPECIES_SENTRET", "ALARM",
     "You came every time. Most times there was no reason.",
     "Still calling. Nobody is coming."),
    ("SPECIES_SHUCKLE", "HOARDING",
     "You have had things out of it. They were not what went in.",
     "Nothing found. Nothing kept."),
    ("SPECIES_SKARMORY", "ARMOURING",
     "You carried it anyway.",
     "Nothing held. Nothing holding."),
    ("SPECIES_SKIPLOOM", "CAPRICE",
     "It was warm often with you. It calls that a decision.",
     "Shut. It calls that one too."),
    ("SPECIES_SLOWBRO", "SHELL",
     "You reached it through the thing on its tail.",
     "Nothing reaching it. Not even that."),
    ("SPECIES_SLUGMA", "SIMMER",
     "Still heading for it. Still not there.",
     "Still not there. Still not cooling."),
    ("SPECIES_SNEASEL", "CUNNING",
     "It waited for you to leave too. You did not notice.",
     "Nobody to wait for. It is not in a hurry."),
    ("SPECIES_SNUBBULL", "WARNING",
     "Nothing failed. It said so every day.",
     "Still nothing failed. Still saying so."),
    ("SPECIES_SPINARAK", "AMBUSH",
     "It did nothing for a long time, with you, on purpose.",
     "Trap built. Nothing doing."),
    ("SPECIES_STANTLER", "ILLUSION",
     "The ground did not tilt. You leaned anyway.",
     "Nobody is looking at its antlers."),
    ("SPECIES_STEELIX", "HARDLINE",
     "You did not cut it.",
     "Still connected. Still the only offer."),
    ("SPECIES_SUDOWOODO", "FAKEROOT",
     "You did not check either.",
     "Still reporting it. Still nothing checking."),
    ("SPECIES_SUNFLORA", "QUOTA",
     "It opened. It still cannot do anything new.",
     "Opened, and put away."),
    ("SPECIES_SUNKERN", "STARVED",
     "You gave it the time.",
     "Everything it needs is here. Still no turn."),
    ("SPECIES_SWINUB", "INSTINCT",
     "It found a great deal. You stopped asking how.",
     "Nothing buried. It keeps walking."),
    ("SPECIES_TEDDIURSA", "COMFORT",
     "The honey is still gone.",
     "Still licking. Still gone."),
    ("SPECIES_TOGETIC", "HOPE",
     "It has stayed up near you.",
     "Nobody near it. It is down."),
    ("SPECIES_TYRANITAR", "GRIEVANCE",
     "It is still owed it. You were not the one who owed it.",
     "Still owed. Still standing in it."),
    ("SPECIES_URSARING", "CRAVING",
     "It took you to all of them.",
     "It remembers every one. It cannot go."),
    ("SPECIES_VAPOREON", "CAREMUSAI",
     "It read a great many rooms for you. It still cannot show the working.",
     "No room to read."),
    ("SPECIES_VENOMOTH", "SPYWARE",
     "It settled on you. It was quiet about it.",
     "Nothing to settle on. Still working."),
    ("SPECIES_VENUSAUR", "ROVERBYTE",
     "It has checked a great deal with you. Some of it was wrong.",
     "A body, and nothing to check it against."),
    ("SPECIES_VICTREEBEL", "TARPIT",
     "Things went in. None came out.",
     "Nothing has entered."),
    ("SPECIES_VILEPLUME", "BADSEED",
     "It settled on everything learning near you.",
     "Nothing learning nearby."),
    ("SPECIES_WARTORTLE", "LOCUS",
     "So far it has held. You did not ask what for either.",
     "Still holding. Nothing testing it."),
    ("SPECIES_WIGGLYTUFF", "HIBERNATE",
     "It came back identical every time.",
     "Switched off. Everything written down."),
    ("SPECIES_XATU", "PRESCIENCE",
     "It saw you coming. It did not move.",
     "Nothing coming. It has seen that too."),
    ("SPECIES_YANMA", "PERIPHERY",
     "It noticed a great deal, too late, all the way.",
     "Everything at once. Nothing in particular."),
    #  The last reachable one. MISSINGNO has none on purpose -- 8.9 says the Index does not hold it, so a
    #  margin in its entry would be a margin in a page that is not there -- and the two eggs are not daemons.
    ("SPECIES_MR_MIME", "MIME",
     "You stopped at the wall a few times yourself.",
     "There is no wall. Nothing has stopped at it."),
    #  T-197b: past reachability now, into the daemons whose ENTRY is ours even though no map places
    #  them. The remaining ~113 cannot have one: their Index entry is still vanilla's prose, and a
    #  margin answers OUR entry -- annotating someone else's writing is not the same feature.
    ("SPECIES_JUMPLUFF", "ABANDON",
     "It came back with you. There was no arrangement.",
     "It let go. Nothing has come back."),
    ("SPECIES_PUPITAR", "BROODING",
     "It went where you went. You still could not ask.",
     "Still sealed. Still moving. Nowhere."),
    ("SPECIES_MAGBY", "CINDER",
     "The work finished a long time ago. It is still warm.",
     "Still warm. Still a hazard. In a box."),
    ("SPECIES_OCTILLERY", "CLINGING",
     "It held on to you. It does that to rocks as well.",
     "Nothing to hold on to. It is holding on."),
    ("SPECIES_ELEKID", "CRANK",
     "You turned it. It has not stopped.",
     "Nobody has turned it."),
    ("SPECIES_AZUMARILL", "ELATION",
     "A great deal was tried. It did not notice.",
     "Nobody is trying. It has not noticed that either."),
    ("SPECIES_DONPHAN", "ENGRAM",
     "Everything you did is in there, in the shape it went in.",
     "Nothing went in. Nothing has worn smooth."),
    ("SPECIES_ARIADOS", "ENTRAPMENT",
     "Things came. The web already fitted them.",
     "Still finished. Still nothing arriving."),
    ("SPECIES_LEDIAN", "GATHERING",
     "There were enough. Nobody agreed the number.",
     "Not enough. Still not agreed."),
    ("SPECIES_BLISSEY", "HEARTBEAT",
     "You listened to the interval and nothing else.",
     "Still reporting. Nothing listening at all now."),
    ("SPECIES_SLOWKING", "KERNEL",
     "It decided a great deal for you, quietly.",
     "Still deciding. Nothing to allow."),
    ("SPECIES_ESPEON", "LENSMUSAI",
     "You pointed it at a great many things. It never turned round.",
     "Pointed at a wall. Very clearly."),
    ("SPECIES_FURRET", "LOOKOUT",
     "It saw over everything. It has still not been relieved.",
     "Nothing to see over. Still not relieved."),
    ("SPECIES_OMASTAR", "MAINFRAME",
     "You brought it a great deal. You took nothing away.",
     "Nothing brought. Nothing taken."),
    ("SPECIES_UMBREON", "MASKMUSAI",
     "It covered a great deal. None of it was removed.",
     "Nothing to cover. It is covering it."),
    ("SPECIES_TYROGUE", "PREMISE",
     "You did not check it either.",
     "Nothing rests on it. Still unchecked."),
    ("SPECIES_WYNAUT", "RANKLE",
     "It remembers where you pushed. It smiled the whole time.",
     "Nobody has pushed. It is still smiling."),
    ("SPECIES_CAMERUPT", "REFORGE",
     "You gave it something else to read.",
     "Left alone. Drawing from its own drawings."),
    ("SPECIES_AMPHAROS", "RELEASE",
     "You saw the moment.",
     "All of it still held. No moment yet."),
    ("SPECIES_CLEFFA", "RESIDUAL",
     "It was in every reading of yours too.",
     "Still in everything. Still no use."),
    ("SPECIES_POLITOED", "SEMAPHORE",
     "It let you through. It did not care which of you it was.",
     "Nothing passing. It is still counting."),
    ("SPECIES_SCIZOR", "SIGKILL",
     "There was no second message.",
     "Still no second message."),
    ("SPECIES_IGGLYBUFF", "STANDBY",
     "You woke it a great many times. It cost less each time.",
     "Doing nothing. Still ready."),
    ("SPECIES_PICHU", "STATIC",
     "You found out by touching it.",
     "Still holding it. Nobody has touched it."),
    ("SPECIES_SMOOCHUM", "TELL",
     "You read it every time. It still does not know.",
     "Nothing to give away. It is giving it away."),
    ("SPECIES_QUAGSIRE", "TORPOR",
     "It arrived everywhere you did, and meant all of it.",
     "No current. It has arrived nowhere, and means that too."),
    ("SPECIES_AZURILL", "VALENCE",
     "The tail was toward you. The rest followed.",
     "Neither toward nor away. The tail has not decided."),
    ("SPECIES_FORRETRESS", "WITHDRAWAL",
     "It has not opened for you either.",
     "Still sealed. Still from the inside."),
]

#  T-188 (the user, 2026-09-24): the EDITION keeps deciding the Index entries, and REASON or INSTINCT -- the
#  choice at the title, which the save keeps as playerGender -- decides the VOICE of the margins. The lines above
#  are REASON's: they notice what you DID, as a record would. INSTINCT's notice what it was LIKE, and only a
#  chosen few are written twice; a daemon with no line here gives both players the one above, which is right,
#  since a reader does not have a second thought about everything.
#
#  DRAFT, every line of it, until the user approves the wording.
INSTINCT = {
    "ROVERCUB": ("It still turns its head at the first town's name. So do you.",
                 "It is waiting at the edge of somewhere. It has been a while."),
    "LABEL":    ("It knew you on sight. It has not had to think about it since.",
                 "It still flinches at the one thing it has been shown."),
    "CLUSTER":  ("You went with it on a feeling. It still feels right.",
                 "It is still sure. Nothing has come near enough to make it unsure."),
    "NIBBLE":   ("Of all of them, this one. You could not say why.",
                 "You picked it out once. It has not been picked since."),
    "HUNCH":    ("You have started trusting it. You did from the start.",
                 "Asleep. It will know before it wakes."),
    "MUSAI":    ("It has felt something now. It has not told you what.",
                 "It is still waiting to feel anything."),
}


def wrap(s):
    out, cur = [], ""
    for w in s.split():
        trial = (cur + " " + w).strip()
        if cur and textwidth(trial) > PANE:
            out.append(cur)
            cur = w
        else:
            cur = trial
    if cur:
        out.append(cur)
    return out


def main():
    over = 0
    body = ['//  Generated by tools/genmargins.py -- edit the tool, not this file (T-197).',
            '//',
            '//  OPUS writes one line under an entry. The entry measures the daemon; the margin notices the',
            '//  PLAYER, and never says so. Two lines per daemon, because what there was to notice depends on',
            '//  whether you carried it or bound it and put it away. Not every entry has one, and that is the',
            '//  point: a reader annotates where they had a thought.',
            '',
            'struct OpusMargin',
            '{',
            '    u16 species;',
            '    const u8 *carried;',
            '    const u8 *neglected;',
            '    const u8 *instinctCarried;     // T-188: NULL, and INSTINCT reads the lines above',
            '    const u8 *instinctNeglected;',
            '};',
            '']
    for sp, name, carried, neglected in MARGINS:
        #  LEMMA MIND has a space in it, and a space in a C identifier is a syntax error rather than a
        #  warning -- so the symbol is the name with its spaces taken out, not the name.
        sym = name.title().replace(" ", "")
        pairs = [("Carried", carried), ("Neglected", neglected)]
        if name in INSTINCT:
            pairs += [("InstinctCarried", INSTINCT[name][0]), ("InstinctNeglected", INSTINCT[name][1])]
        for kind, text in pairs:
            lines = wrap(text)
            widest = max(textwidth(l) for l in lines)
            bad = widest > PANE or len(lines) > MAXLINES
            over += bad
            print("  %-10s %-17s %3dpx %d lines%s  %s"
                  % (name, kind.lower(), widest, len(lines), " !!" if bad else "  ", " / ".join(lines)))
            body.append('static const u8 sOpusMargin_%s_%s[] = _("%s");' % (sym, kind, "\\n".join(lines)))
        body.append('')
    body.append('static const struct OpusMargin sOpusMargins[] = {')
    for sp, name, _c, _n in MARGINS:
        sym = name.title().replace(" ", "")
        inst = ("sOpusMargin_%s_InstinctCarried, sOpusMargin_%s_InstinctNeglected" % (sym, sym)
                if name in INSTINCT else "NULL, NULL")
        body.append('    { %-22s sOpusMargin_%s_Carried, sOpusMargin_%s_Neglected, %s },'
                    % (sp + ",", sym, sym, inst))
    body += ['};', '']
    missing = sorted(set(INSTINCT) - {m[1] for m in MARGINS})
    if missing:
        sys.exit("  INSTINCT names a daemon with no margin: %s" % ", ".join(missing))
    print("\n  %d margin(s) for %d daemons, %d of them written again for INSTINCT; %d over the %dpx pane"
          % (2 * len(MARGINS) + 2 * len(INSTINCT), len(MARGINS), len(INSTINCT), over, PANE))
    if WRITE:
        open(OUT, "w", encoding="utf-8").write("\n".join(body))
        print("  written %s" % os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
