#!/usr/bin/env python3
"""OPUS's margin lines, wrapped to the Index entry's own pane (T-197; vision.md 4.2).

    python3 tools/genmargins.py            # report every line, measured
    python3 tools/genmargins.py --write     # write src/data/opus_margins.h

WHAT A MARGIN LINE IS. The entry measures the daemon -- height, weight, type, stats, and the thin sentence
4.2 is about. The margin notices the PLAYER, and never says so. It is never a measurement, never advice,
never a hint, and it only makes sense read against the entry above it.

TWO LINES, because what OPUS noticed depends on what you did. A daemon you levelled gets one line; a daemon
you bound and put away gets another. The second is not a scold -- it is the same quiet noticing, aimed at the
thing you did not do.

NOT EVERY ENTRY HAS ONE, and that is the point: a reader annotates where they had a thought.

THE PANE is the entry's own, demonstrated rather than declared -- 234px and four lines, which is the widest
line and the most lines the 386 entries use.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GBA = os.path.join(ROOT, "engineGba")
OUT = os.path.join(GBA, "src/data/opus_margins.h")
PANE, MAXLINES = 234, 4
WRITE = "--write" in sys.argv

_src = open(os.path.join(ROOT, "tools/port_vocab.py"), encoding="utf-8").read()
_ns = {"__name__": "port_vocab_font", "__file__": os.path.join(ROOT, "tools/port_vocab.py")}
exec(compile(_src.split("# ------------------------------------------------------- names, derived")[0],
             "port_vocab.py", "exec"), _ns)
textwidth = _ns["textwidth"]

#  (species constant, our name, carried, neglected)
MARGINS = [
    ("SPECIES_BULBASAUR", "ROVERCUB",
     "It remembers the way back to the first town. You have not gone that way in some time.",
     "It is not being carried past anything."),
    ("SPECIES_CHARMANDER", "LABEL",
     "It has met you now. It has not changed the answer.",
     "It is still holding the one example. Nobody has shown it a second."),
    ("SPECIES_SQUIRTLE", "CLUSTER",
     "You have not checked the guess either.",
     "The guess has not changed. Nothing has been near it."),
    ("SPECIES_RATTATA", "NIBBLE",
     "You have met a great many. This is the one you kept.",
     "You kept this one. You have not filed it with anything."),
    ("SPECIES_PIDGEY", "PACKET",
     "It still does not ask. You have stopped noticing that.",
     "It has not been sent anywhere. It is still carrying it."),
    ("SPECIES_ABRA", "HUNCH",
     "You have started trusting it. There is still no working.",
     "Asleep. Nothing has needed an answer from it."),
    ("SPECIES_MAGNEMITE", "SENTINEL",
     "It has watched more of your fights than it has been in.",
     "It is still not looking away. There is nothing in there to watch."),
    ("SPECIES_DITTO", "MOCK",
     "You have seen it be other daemons. You have never seen it.",
     "It has nothing to look at. You do not know what it is like then."),
    ("SPECIES_PORYGON", "SUBSTRATE",
     "You carry it differently. You have not said why.",
     "Where it is has not changed in a long time."),
    ("SPECIES_GASTLY", "DANGLING",
     "It has been out in front of you more than most. It is still mostly not there.",
     "It does not have to be here either."),
    ("SPECIES_EEVEE", "MUSAI",
     "It has been shown something now.",
     "It is still waiting to be shown anything."),
    #  The best of these answer the entry's LAST SENTENCE, which is where an entry states the thing it is
    #  sure of. HEAP has never been asked to give one back; STUB says nobody came back for it. A margin that
    #  contradicts the entry above it is the strongest form of this: the record was right when it was written.
    ("SPECIES_GEODUDE", "HEAP",
     "It has been asked now. It gave one back.",
     "You put it down and left it. It is holding that too."),
    ("SPECIES_SPEAROW", "PING",
     "You have answered every time. It still asks.",
     "It is still asking. Nothing has answered in a long time."),
    ("SPECIES_ZUBAT", "ECHO",
     "It has built every room you have walked it through. You have not checked one.",
     "Nothing has come back. It has not stopped calling."),
    ("SPECIES_CATERPIE", "CRAWLER",
     "It has not finished. You have gone a long way with it.",
     "It stopped when you stopped. It had not finished."),
    ("SPECIES_WEEDLE", "SCRAPER",
     "Nobody has asked you for it back either.",
     "It took nothing. Nobody minded."),
    ("SPECIES_PIKACHU", "SPIKE",
     "You were counting.",
     "It has not fired. Nothing was counting anyway."),
    ("SPECIES_NIDORAN_F", "FORK",
     "You have one of them. You do not know which.",
     "It has not split. There is only the one, and it still cannot tell."),
    ("SPECIES_MANKEY", "PREEMPT",
     "It has gone first every time. You have stopped choosing.",
     "Nothing has been interrupted. It has not been first in a long time."),
    ("SPECIES_MACHOP", "PROOF",
     "It has not skipped one yet. You have.",
     "It is still on the first thing."),
    ("SPECIES_MAGIKARP", "STUB",
     "Somebody came back for it.",
     "You did not come back for it either."),
    ("SPECIES_PSYDUCK", "FAULT",
     "It has halted you a great many times. You waited every time.",
     "It is still waiting. So is whatever needed it."),
    ("SPECIES_ODDISH", "SPRAWL",
     "It has spread as far as you have walked.",
     "It has not spread. It is only buried."),
    ("SPECIES_BELLSPROUT", "SNARE",
     "It has closed on things for you. It is open again now.",
     "Still open. Nothing has entered."),
    ("SPECIES_JIGGLYPUFF", "SUSPEND",
     "You have used it to stop things. None of them ended.",
     "It has stopped, and nothing is happening to it."),
    ("SPECIES_MEOWTH", "COOKIE",
     "You set it down and picked it up again. It is the same one.",
     "Set down. Not picked up again."),
    ("SPECIES_DIGLETT", "TAPPOINT",
     "It has read everything you walked past. You did not.",
     "Nothing goes past in there."),
    #  The middle of the game. CANARY's is the one to read against 4.2: the daemon changes faster than
    #  anything measuring it, and the thing measuring it is the Index.
    ("SPECIES_EKANS", "WORM",
     "It has been in more places than you have looked.",
     "It has not stopped. You simply stopped looking."),
    ("SPECIES_SANDSHREW", "SECTOR",
     "You have got things back from it. You never checked what else was in there.",
     "Everything in it can still be got back. Nobody has asked."),
    ("SPECIES_VULPIX", "FLICKER",
     "Still neither. You have stopped checking which.",
     "Still not a fault. Still not looked at."),
    ("SPECIES_GROWLITHE", "SENTRY",
     "It has raised the alarm every time. You answered most of them.",
     "It is still watching. Nobody is listening for the alarm."),
    ("SPECIES_POLIWAG", "LOOP",
     "You have not told it when to stop either.",
     "Still going round. Nobody has come back to it."),
    #  NOT "caught": 1.1 renamed the capture verb, so port_vocab reads it as bind and writes "It has bound a
    #  great deal" -- which is what a PLAYER does to a daemon, not what a net does to what drifts into it.
    #  The word goes rather than the rule.
    ("SPECIES_TENTACOOL", "DRIFTNET",
     "It has taken a great deal. None of it was aimed at.",
     "There is no current in there."),
    ("SPECIES_SLOWPOKE", "LATENCY",
     "You have waited for it. It was right every time.",
     "The answer is ready. Nothing has asked the question."),
    ("SPECIES_GRIMER", "DEADLETTER",
     "You decided on somewhere. It is still keeping all of it.",
     "Kept. Somewhere nobody decided on."),
    ("SPECIES_SHELLDER", "CAPSULE",
     "You have stopped asking it to open.",
     "Still closed. Nobody has asked in a long time."),
    ("SPECIES_ONIX", "BACKBONE",
     "A great deal is built on it now.",
     "Nothing has been built on it."),
    ("SPECIES_KRABBY", "ACQUIRE",
     "It has led with that one every time.",
     "Nothing in there to lead with."),
    ("SPECIES_VOLTORB", "FUSE",
     "It has had its moment. You were there.",
     "Its moment has not come. It is still waiting to fail."),
    ("SPECIES_CUBONE", "ARTEFACT",
     "You have called it that name a great many times.",
     "Nobody has called it anything."),
    ("SPECIES_KOFFING", "EXHAUST",
     "It is still leaking. It is still up.",
     "Still leaking, into a box, and still up."),
    ("SPECIES_HORSEA", "BOTTLENECK",
     "Everything you sent through it came out slower.",
     "Nothing has passed through it."),
    ("SPECIES_GOLDEEN", "SPAWN",
     "It has started nothing yet. It is still swimming against it.",
     "Still against the current, in a box with no current."),
    ("SPECIES_STARYU", "BEACON",
     "It has not missed an interval. You have not counted one.",
     "Still emitting, at the same interval, to nobody."),
    ("SPECIES_SCYTHER", "REAPER",
     "You have seen the cut later, every time.",
     "Nothing it cut has shown up yet."),
    ("SPECIES_LAPRAS", "FERRY",
     "You asked. It has never mentioned that it could have gone alone.",
     "It is still waiting to be asked."),
    ("SPECIES_SNORLAX", "DEADLOCK",
     "Something outside came.",
     "You are outside. You did not come."),
    ("SPECIES_DRATINI", "CANARY",
     "It has changed a great deal. The Index says what it always said.",
     "Changing in there, faster than anything measuring it."),
    ("SPECIES_TOGEPI", "TRUST",
     "It came out facing you.",
     "It is still facing whoever was holding it."),
    ("SPECIES_MARILL", "MOOD",
     "It has been at every level you have been at.",
     "The water in there does not move."),
    ("SPECIES_WOOPER", "APATHY",
     "Things happened. It was told. It stayed.",
     "Nothing has been reported to it."),
    ("SPECIES_MURKROW", "OMEN",
     "It has arrived before a great many things. You stopped asking too.",
     "Nothing has arrived. Neither has it."),
    ("SPECIES_MISDREAVUS", "DREAD",
     "You expected it every time. It has eaten well.",
     "Nobody is expecting it. It is not eating."),
    #  The late game. HAUNTPROC's carried line is the one that answers the SCREEN rather than the entry:
    #  its entry says it has no entry in any list, and it is being read off a list.
    ("SPECIES_HAUNTER", "RESPAWN",
     "It has ended again since you had it. You know what started it.",
     "It has not ended again. Nothing has started it either."),
    ("SPECIES_GENGAR", "HAUNTPROC",
     "It has an entry in this list. That is all it has.",
     "No parent, no terminal, and one entry, unread."),
    ("SPECIES_DROWZEE", "LULL",
     "It has eaten a great many things you were going to do.",
     "Off the schedule. Nothing to feed on."),
    ("SPECIES_HYPNO", "BUSYWAIT",
     "It has held yours. You did not notice what stopped.",
     "Nothing is running. It is holding nothing's attention."),
    ("SPECIES_EXEGGCUTE", "BOOTSTRAP",
     "They have voted a great many times. You were never asked.",
     "Still voting. Still nobody in charge."),
    ("SPECIES_LICKITUNG", "SLURP",
     "It has a reading of everywhere you have been.",
     "There is nothing in there to reach."),
    ("SPECIES_RHYHORN", "HARDCODE",
     "You picked the direction. It stopped picking.",
     "Still pointed the way it was pointed."),
    ("SPECIES_CHANSEY", "UPTIME",
     "It has not stopped. A good deal of that was for you.",
     "It has still never stopped. Nothing near it is failing."),
    ("SPECIES_TANGELA", "SPAGHETTI",
     "You are still here. You cannot explain it either.",
     "Nobody who could explain it is still here. Nobody has asked."),
    ("SPECIES_KANGASKHAN", "KEEPER",
     "It has not put it down once.",
     "Still carrying. Still has not put it down."),
    ("SPECIES_JYNX", "COLDREAD",
     "It has been right more often since it met you.",
     "It has nothing to be right about."),
    ("SPECIES_ELECTABUZZ", "DYNAMO",
     "You kept it moving. It has not stopped.",
     "Not moving. No current."),
    ("SPECIES_MAGMAR", "FORGE",
     "Things were changed. None of them changed back.",
     "Still at temperature. Nothing has been put in."),
    ("SPECIES_PINSIR", "BLOCKING",
     "Everything it closed on stopped moving.",
     "Closed on nothing, and waiting for it to stop."),
    ("SPECIES_TAUROS", "STAMPEDE",
     "You moved first a great many times. Nothing decided that either.",
     "None of them has moved."),
    ("SPECIES_AERODACTYL", "FOSSILNET",
     "It started again. You still have not asked how.",
     "Recovered whole, put somewhere, and not asked."),
    ("SPECIES_ARTICUNO", "ORPHEUS",
     "It came up.",
     "It is not four floors down any more. It still will not come up."),
    ("SPECIES_ZAPDOS", "ASCLEPIUS",
     "It has restarted things for you. You did not ask how either.",
     "Nothing near it has stopped. It is waiting."),
    ("SPECIES_MOLTRES", "PROMETHEUS",
     "You were standing there.",
     "It is still holding it. Nobody is standing there."),
    ("SPECIES_MEWTWO", "STARR",
     "It has read a great deal of itself since you had it.",
     "Still reading itself. Nothing tells it to stop."),
    ("SPECIES_MEW", "ARTSAI",
     "It has stood where you are standing. You have not tried the other way.",
     "It has not stood anywhere in a long time."),
    ("SPECIES_PORYGON2", "OVERLAY",
     "You have only ever read the second layer.",
     "Both layers. Neither read."),
    ("SPECIES_UNOWN", "SYMBOL",
     "You have carried one of the twenty-six. It did not say anything.",
     "Still twenty-six. Still unread."),
    ("SPECIES_WOBBUFFET", "RESENTMENT",
     "Everything came back. You were there for all of it.",
     "Nothing has been done to it. Nothing is coming back."),
    ("SPECIES_GIRAFARIG", "DUPLEX",
     "Both ends have been busy. Neither has been told.",
     "Both ends quiet. Still not telling each other."),
    ("SPECIES_SMEARGLE", "IMITATION",
     "It has done everything you have done. Nobody has seen it do one of its own.",
     "It has not seen anything done."),
    ("SPECIES_MILTANK", "CACHE",
     "It had what you wanted next, every time.",
     "Nothing nearby wants anything."),
    #  And the rest of what a player meets walking through Kanto.
    ("SPECIES_METAPOD", "PENDING",
     "It has been processed. It had stopped counting by then.",
     "Still waiting. Still not counting."),
    ("SPECIES_BUTTERFREE", "INDEXER",
     "It has filed a great deal of your going about. What it dropped, neither of you knows.",
     "Nothing to file. Nothing dropped."),
    ("SPECIES_KAKUNA", "BUFFER",
     "Somewhere was found. It let go.",
     "It is still holding. Somewhere has not been found."),
    ("SPECIES_BEEDRILL", "INJECTOR",
     "You have never checked what it put there.",
     "Nothing has read it. The instructions are still in."),
    ("SPECIES_PIDGEOTTO", "RELAY",
     "It has never opened one. You have not either.",
     "Nothing has been handed to it."),
    ("SPECIES_RATICATE", "OVERFLOW",
     "It is counting still. You stopped looking at the number.",
     "Nothing is watching. It is counting still."),
    ("SPECIES_FEAROW", "FLOOD",
     "You answered one of them.",
     "All of them are still waiting."),
    ("SPECIES_ARBOK", "OUTBREAK",
     "You have been watching the number.",
     "Still a number. Nobody is watching either."),
    ("SPECIES_RAICHU", "SURGE",
     "It has not stopped. You stopped reading it.",
     "Still a condition. Still nothing reading it."),
    ("SPECIES_SANDSLASH", "PARTITION",
     "Both halves have been walked. It kept them apart anyway.",
     "Both halves are in there. Still apart."),
    ("SPECIES_NIDORINO", "PREDICTOR",
     "It has been wrong with you, and put it all back.",
     "It has not guessed at anything."),
    ("SPECIES_CLEFAIRY", "ANOMALY",
     "You have measured it a great deal. The measurements are still good.",
     "Still unpredicted. Still measured, and still fine."),
    ("SPECIES_NINETALES", "OVERRUN",
     "Nothing intervened. You were there the whole time.",
     "Still past it. Still nothing intervening."),
    ("SPECIES_GOLBAT", "TRACER",
     "It followed one back to you.",
     "No path to follow."),
    ("SPECIES_PARAS", "PAYLOAD",
     "You invited one of them.",
     "Both still there. Still only one invited."),
    ("SPECIES_VENONAT", "RESIDENT",
     "It was already in before you looked. It still is.",
     "Already inside. Nobody has looked."),
    ("SPECIES_DUGTRIO", "WIRETAP",
     "All three heard everywhere you went. They agree.",
     "Three of them, under nothing, agreeing about it."),
    ("SPECIES_PERSIAN", "TRACKER",
     "It has not lost you yet.",
     "Nothing to follow. It has not lost that either."),
    ("SPECIES_GOLDUCK", "HANDLER",
     "It has seen yours before. It was calm about that too.",
     "Nothing has stopped near it."),
    ("SPECIES_PRIMEAPE", "LIVELOCK",
     "One of them went somewhere with you. The other has not noticed.",
     "Still moving. Still nowhere."),
    ("SPECIES_ARCANINE", "GUARDIAN",
     "Things came. It was not at the door.",
     "Still at the door. Still right."),
    ("SPECIES_POLIWHIRL", "SPINLOCK",
     "You let it pass. It had been checking the whole time.",
     "Still checking. It stopped being cheaper a long time ago."),
    ("SPECIES_KADABRA", "INFERENCE",
     "You took the fourth thing every time and never asked.",
     "It has not been given three of anything."),
    ("SPECIES_MACHOKE", "THEOREM",
     "You have started from it a great many times.",
     "It is still carrying the one result."),
    ("SPECIES_WEEPINBELL", "HONEYPOT",
     "You came in. It was written down.",
     "Still open. Nothing written."),
    ("SPECIES_TENTACRUEL", "DRAGNET",
     "It kept everything. Afterwards has not happened.",
     "Nothing swept. Nothing to sort."),
    ("SPECIES_GRAVELER", "STACK",
     "You have taken the last thing off it many times. What is under has waited.",
     "Nothing has been taken off it."),
    ("SPECIES_PONYTA", "HOTPATH",
     "You wore it.",
     "Cold."),
    ("SPECIES_MAGNETON", "QUORUM",
     "All three saw everything you did.",
     "Three of them, agreeing about nothing."),
    ("SPECIES_FARFETCHD", "EDGECASE",
     "You did not plan for it either.",
     "Still carrying it. Still nobody planning."),
    ("SPECIES_DODRIO", "TRIPLECORE",
     "Three directions watched, the whole way.",
     "Three directions. All of them a wall."),
    ("SPECIES_DEWGONG", "ARCHIVER",
     "It is still paying. You have not asked what for.",
     "Still paying. Nothing was asked of it."),
    ("SPECIES_MUK", "LANDFILL",
     "Still reacting. You have been carrying that.",
     "Still reacting, in there, where nobody put it."),
    ("SPECIES_CLOYSTER", "COLDVAULT",
     "Still nothing read out of it. You carried it anyway.",
     "Still nothing read. Still not known to open."),
    ("SPECIES_HITMONLEE", "AXIOMKICK",
     "Every step of it was legal. It still reached further than it should.",
     "Nothing to reach."),
    ("SPECIES_HITMONCHAN", "REBUTTAL",
     "It has answered a great deal. It has still never opened.",
     "Nothing said. Nothing answered."),
    ("SPECIES_WEEZING", "SMOGSTACK",
     "It has been running the whole time you have.",
     "No work. Still running."),
    ("SPECIES_RHYDON", "MIGRATE",
     "You wanted it somewhere. It did not ask which was which.",
     "Nothing moved. Nothing wanted."),
    ("SPECIES_SEADRA", "BACKPRESS",
     "It held position the whole way.",
     "Still running. The water stopped."),
    ("SPECIES_SEAKING", "UPSTREAM",
     "It has not been told. It is still going.",
     "Still not told. Not going either."),
    ("SPECIES_STARMIE", "CRON",
     "It has not varied. You have not asked it to.",
     "Still on the interval. Still nothing asking."),
    ("SPECIES_GYARADOS", "ESCALATE",
     "You left it alone long enough.",
     "Left alone. Still accumulating."),
    ("SPECIES_OMANYTE", "MAGTAPE",
     "You have read some of it. It does not go back.",
     "Wound, and unread, and only one direction."),
    ("SPECIES_KABUTO", "DRUM",
     "It has not been opened. It is still spinning.",
     "Still sealed. Still spinning. Nothing has asked."),
    #  T-197a: the target is not 386 and never was -- it is every daemon a player can REACH, which
    #  tools/gbareach.py answers: 213. At 124 the coverage of those was 57%, which is a shortfall and not a
    #  stopping point. These are the rest of what someone can actually carry.
    ("SPECIES_AIPOM", "GRASP",
     "Everything you walked past was picked up and turned over.",
     "Nothing to pass. Nothing turned over."),
    ("SPECIES_ALAKAZAM", "CONJECTURE",
     "Still unproved. You have not tried either.",
     "The waiting has got longer."),
    ("SPECIES_BELLOSSOM", "GOLDSET",
     "You have used the answers. You did not check the hands.",
     "Still checked once. Still nobody checking the hands."),
    ("SPECIES_BLASTOISE", "MANIFOLD",
     "It showed you the shape. You called it something anyway.",
     "The shape is still there. Nobody has looked at it."),
    ("SPECIES_CHARIZARD", "CANON",
     "You were filed as an error once. The file is still not read.",
     "No new cases. Nothing to file."),
    ("SPECIES_CHARMELEON", "RUBRIC",
     "You did not check the rule either.",
     "Still applying it. To nothing."),
    ("SPECIES_CHINCHOU", "PILOT",
     "You took it into the dark. The line was live the whole time.",
     "Still lit. Nothing to show."),
    ("SPECIES_CLEFABLE", "OUTLIER",
     "You did not drop it.",
     "Dropped again."),
    ("SPECIES_CROBAT", "MULTICAST",
     "You never asked either.",
     "Four places, and it has been to none of them."),
    ("SPECIES_DELIBIRD", "REPAY",
     "The amounts still do not match. It is still coming.",
     "Nobody has fed it. It has nothing to bring."),
    ("SPECIES_DEOXYS", "PROTEUS",
     "You held on. The last one is the one you have.",
     "Still changing. Nobody is looking."),
    ("SPECIES_DODUO", "DUALCORE",
     "They agreed, eventually, every time.",
     "No task. They are still agreeing about it."),
    ("SPECIES_DRAGONAIR", "EMERGENCE",
     "Nothing was added. You were there for all of it.",
     "Nothing added. Nothing observed."),
    ("SPECIES_DRAGONITE", "SINGULAR",
     "It arrived reliably. You stopped being surprised.",
     "Reliable, and unobserved."),
    ("SPECIES_DUNSPARCE", "BLINDSPOT",
     "You saw one.",
     "You have one. You have not seen it."),
    ("SPECIES_ELECTRODE", "BREAKER",
     "It has not had to yet.",
     "Rated for nothing. Nothing coming."),
    ("SPECIES_EXEGGUTOR", "ENSEMBLE",
     "You have only ever heard the single answer.",
     "Several heads, and nothing to answer."),
    ("SPECIES_FLAAFFY", "BUILDUP",
     "You spent some of it. Everyone is still careful.",
     "Still going up. Nobody nearby."),
    ("SPECIES_FLAREON", "CODEMUSAI",
     "Every rule it met came from you. It did not ask.",
     "No rule. It has not stopped."),
    ("SPECIES_GLOOM", "SKEW",
     "Everything downwind of you grew differently.",
     "Still dripping. Nothing downwind."),
    ("SPECIES_GOLEM", "MONOLITH",
     "You took all of it, every time.",
     "Still one piece. Still efficient."),
    ("SPECIES_HERACROSS", "DRIVE",
     "The thing moved. It has not stopped.",
     "Nothing to push at. It has not stopped."),
    ("SPECIES_HITMONTOP", "CIRCULAR",
     "It finished a great many times. You went somewhere.",
     "Back where it started. Very fast."),
    ("SPECIES_HOOTHOOT", "POLL",
     "It has a great many answers about you. You have not read one.",
     "Still asking. The answer has not changed."),
    ("SPECIES_HOPPIP", "WHIM",
     "It went where you went. It says it chose.",
     "No air. It still says it chose."),
    ("SPECIES_HOUNDOOM", "OBSESSION",
     "You remember it.",
     "Still the one cry. Nobody has heard it."),
    ("SPECIES_HOUNDOUR", "FIXATION",
     "It picked you.",
     "It has not picked anything."),
    ("SPECIES_HO_OH", "PHOENIX",
     "It has started itself since you had it. You did nothing.",
     "It has not needed to start."),
    ("SPECIES_IVYSAUR", "ROVERSEER",
     "It has been outside. The answers are the same.",
     "Still inside. Still answering."),
    ("SPECIES_JOLTEON", "SEEKMUSAI",
     "You were shown the nearest match a great many times. Nobody told you either.",
     "Nothing shown. Nothing matched."),
    ("SPECIES_KABUTOPS", "PUNCHCARD",
     "A great deal was cut. None of it has been read back.",
     "Nothing cut. Nothing read."),
    ("SPECIES_KINGDRA", "TURBULENCE",
     "Nothing was wrong when it left you either.",
     "Nothing upstream. Nothing arriving."),
    ("SPECIES_KINGLER", "LOCKUP",
     "It closed on a great deal. It opened slowly each time.",
     "Closed. Nothing in it."),
    ("SPECIES_LANTURN", "SOUNDING",
     "It found the bottom every time. You did not ask how far.",
     "Still sending. Nothing coming back."),
    ("SPECIES_LARVITAR", "RUMINATE",
     "It is out. It is still eating.",
     "Still eating. Still in."),
    ("SPECIES_LEDYBA", "HUDDLE",
     "It was not alone.",
     "Alone."),
    ("SPECIES_LUGIA", "TRITON",
     "It has said nothing to you either.",
     "Nothing quarrelling. Nothing to settle."),
    ("SPECIES_MACHAMP", "LEMMA MIND",
     "It held all of it. You held one part.",
     "Still holding all of it."),
    ("SPECIES_MAGCARGO", "CALLOUS",
     "You touched the shell a great many times.",
     "Still molten. Nothing touching."),
    ("SPECIES_MANTINE", "BUOYANCY",
     "You put a great deal on it. It rose anyway.",
     "Nothing on it. Still rising."),
    ("SPECIES_MAREEP", "TENSION",
     "You found out how much.",
     "Still gathering. Nobody has touched it."),
    ("SPECIES_MAROWAK", "COREFILE",
     "It carried it everywhere you went. It has still not put it down.",
     "Still carrying it. Nowhere."),
    ("SPECIES_NATU", "VIGILANCE",
     "It still has not happened. It still has not looked away.",
     "Nothing to watch. It has not looked away."),
    ("SPECIES_NIDOKING", "PIPELINE",
     "You never interrupted it.",
     "Six things, all stopped, none finished."),
    ("SPECIES_NIDOQUEEN", "SCHEDULER",
     "You decided instead. It did not appeal either.",
     "Nothing to decide about. Still deciding."),
    ("SPECIES_NIDORAN_M", "BRANCH",
     "It picked early every time. You did not check the other way.",
     "No steps. Nothing to pick."),
    ("SPECIES_NIDORINA", "THREAD",
     "You changed one of them.",
     "Beside nothing. Sharing it with nobody."),
    ("SPECIES_NOCTOWL", "SUPERVISOR",
     "It started you again more than once.",
     "Nothing moving. Nothing to restart."),
    ("SPECIES_NUMEL", "PIXELBYTE",
     "It has drawn a great deal for you. It still cannot say what.",
     "Still static. Nothing taken away."),
    ("SPECIES_PARASECT", "ROOTKIT",
     "Nothing looked different to you either.",
     "Still running it. Still nothing looks different."),
    ("SPECIES_PHANPY", "RECALL",
     "It has a year of you, exactly.",
     "It is keeping everything. Nothing has happened."),
    ("SPECIES_PIDGEOT", "BROADCAST",
     "Some of it landed on you. It is still sending.",
     "Still sending. Nowhere is listening."),
    ("SPECIES_PILOSWINE", "IMPULSE",
     "It charged a great many times. It was usually right.",
     "Nothing to charge at. It still cannot see."),
    ("SPECIES_PINECO", "STARTLE",
     "You touched it once.",
     "Still hanging. Months."),
    ("SPECIES_POLIWRATH", "MUTEX",
     "You held it. You let go.",
     "Nobody is holding it. Everyone is waiting anyway."),
    ("SPECIES_QWILFISH", "BRISTLE",
     "It is still that size.",
     "Nothing has threatened it. It is still that size."),
    ("SPECIES_RAPIDASH", "OVERDRIVE",
     "You never made it check.",
     "Still not stopping. Not going anywhere."),
    ("SPECIES_REMORAID", "ATTACHMENT",
     "It fastened to you. It still did not choose.",
     "Nothing larger. Nowhere."),
    ("SPECIES_SEEL", "HEATSINK",
     "It took a great deal and did not warm.",
     "Nothing to draw. Still cold."),
    ("SPECIES_SENTRET", "ALARM",
     "You came every time. Most times there was no reason.",
     "Still calling. Nobody is coming."),
    ("SPECIES_SHUCKLE", "HOARDING",
     "You have had things out of it. They were not what went in.",
     "Nothing found. Nothing kept."),
    ("SPECIES_SKARMORY", "ARMOURING",
     "You carried it anyway.",
     "Nothing held. Nothing holding."),
    ("SPECIES_SKIPLOOM", "CAPRICE",
     "It was warm often with you. It calls that a decision.",
     "Shut. It calls that one too."),
    ("SPECIES_SLOWBRO", "SHELL",
     "You reached it through the thing on its tail.",
     "Nothing reaching it. Not even that."),
    ("SPECIES_SLUGMA", "SIMMER",
     "Still heading for it. Still not there.",
     "Still not there. Still not cooling."),
    ("SPECIES_SNEASEL", "CUNNING",
     "It waited for you to leave too. You did not notice.",
     "Nobody to wait for. It is not in a hurry."),
    ("SPECIES_SNUBBULL", "WARNING",
     "Nothing failed. It said so every day.",
     "Still nothing failed. Still saying so."),
    ("SPECIES_SPINARAK", "AMBUSH",
     "It did nothing for a long time, with you, on purpose.",
     "Trap built. Nothing doing."),
    ("SPECIES_STANTLER", "ILLUSION",
     "The ground did not tilt. You leaned anyway.",
     "Nobody is looking at its antlers."),
    ("SPECIES_STEELIX", "HARDLINE",
     "You did not cut it.",
     "Still connected. Still the only offer."),
    ("SPECIES_SUDOWOODO", "FAKEROOT",
     "You did not check either.",
     "Still reporting it. Still nothing checking."),
    ("SPECIES_SUNFLORA", "QUOTA",
     "It opened. It still cannot do anything new.",
     "Opened, and put away."),
    ("SPECIES_SUNKERN", "STARVED",
     "You gave it the time.",
     "Everything it needs is here. Still no turn."),
    ("SPECIES_SWINUB", "INSTINCT",
     "It found a great deal. You stopped asking how.",
     "Nothing buried. It keeps walking."),
    ("SPECIES_TEDDIURSA", "COMFORT",
     "The honey is still gone.",
     "Still licking. Still gone."),
    ("SPECIES_TOGETIC", "HOPE",
     "It has stayed up near you.",
     "Nobody near it. It is down."),
    ("SPECIES_TYRANITAR", "GRIEVANCE",
     "It is still owed it. You were not the one who owed it.",
     "Still owed. Still standing in it."),
    ("SPECIES_URSARING", "CRAVING",
     "It took you to all of them.",
     "It remembers every one. It cannot go."),
    ("SPECIES_VAPOREON", "CAREMUSAI",
     "It read a great many rooms for you. It still cannot show the working.",
     "No room to read."),
    ("SPECIES_VENOMOTH", "SPYWARE",
     "It settled on you. It was quiet about it.",
     "Nothing to settle on. Still working."),
    ("SPECIES_VENUSAUR", "ROVERBYTE",
     "It has checked a great deal with you. Some of it was wrong.",
     "A body, and nothing to check it against."),
    ("SPECIES_VICTREEBEL", "TARPIT",
     "Things went in. None came out.",
     "Nothing has entered."),
    ("SPECIES_VILEPLUME", "BADSEED",
     "It settled on everything learning near you.",
     "Nothing learning nearby."),
    ("SPECIES_WARTORTLE", "LOCUS",
     "So far it has held. You did not ask what for either.",
     "Still holding. Nothing testing it."),
    ("SPECIES_WIGGLYTUFF", "HIBERNATE",
     "It came back identical every time.",
     "Switched off. Everything written down."),
    ("SPECIES_XATU", "PRESCIENCE",
     "It saw you coming. It did not move.",
     "Nothing coming. It has seen that too."),
    ("SPECIES_YANMA", "PERIPHERY",
     "It noticed a great deal, too late, all the way.",
     "Everything at once. Nothing in particular."),
    #  The last reachable one. MISSINGNO has none on purpose -- 8.9 says the Index does not hold it, so a
    #  margin in its entry would be a margin in a page that is not there -- and the two eggs are not daemons.
    ("SPECIES_MR_MIME", "MIME",
     "You stopped at the wall a few times yourself.",
     "There is no wall. Nothing has stopped at it."),
    #  T-197b: past reachability now, into the daemons whose ENTRY is ours even though no map places
    #  them. The remaining ~113 cannot have one: their Index entry is still vanilla's prose, and a
    #  margin answers OUR entry -- annotating someone else's writing is not the same feature.
    ("SPECIES_JUMPLUFF", "ABANDON",
     "It came back with you. There was no arrangement.",
     "It let go. Nothing has come back."),
    ("SPECIES_PUPITAR", "BROODING",
     "It went where you went. You still could not ask.",
     "Still sealed. Still moving. Nowhere."),
    ("SPECIES_MAGBY", "CINDER",
     "The work finished a long time ago. It is still warm.",
     "Still warm. Still a hazard. In a box."),
    ("SPECIES_OCTILLERY", "CLINGING",
     "It held on to you. It does that to rocks as well.",
     "Nothing to hold on to. It is holding on."),
    ("SPECIES_ELEKID", "CRANK",
     "You turned it. It has not stopped.",
     "Nobody has turned it."),
    ("SPECIES_AZUMARILL", "ELATION",
     "A great deal was tried. It did not notice.",
     "Nobody is trying. It has not noticed that either."),
    ("SPECIES_DONPHAN", "ENGRAM",
     "Everything you did is in there, in the shape it went in.",
     "Nothing went in. Nothing has worn smooth."),
    ("SPECIES_ARIADOS", "ENTRAPMENT",
     "Things came. The web already fitted them.",
     "Still finished. Still nothing arriving."),
    ("SPECIES_LEDIAN", "GATHERING",
     "There were enough. Nobody agreed the number.",
     "Not enough. Still not agreed."),
    ("SPECIES_BLISSEY", "HEARTBEAT",
     "You listened to the interval and nothing else.",
     "Still reporting. Nothing listening at all now."),
    ("SPECIES_SLOWKING", "KERNEL",
     "It decided a great deal for you, quietly.",
     "Still deciding. Nothing to allow."),
    ("SPECIES_ESPEON", "LENSMUSAI",
     "You pointed it at a great many things. It never turned round.",
     "Pointed at a wall. Very clearly."),
    ("SPECIES_FURRET", "LOOKOUT",
     "It saw over everything. It has still not been relieved.",
     "Nothing to see over. Still not relieved."),
    ("SPECIES_OMASTAR", "MAINFRAME",
     "You brought it a great deal. You took nothing away.",
     "Nothing brought. Nothing taken."),
    ("SPECIES_UMBREON", "MASKMUSAI",
     "It covered a great deal. None of it was removed.",
     "Nothing to cover. It is covering it."),
    ("SPECIES_TYROGUE", "PREMISE",
     "You did not check it either.",
     "Nothing rests on it. Still unchecked."),
    ("SPECIES_WYNAUT", "RANKLE",
     "It remembers where you pushed. It smiled the whole time.",
     "Nobody has pushed. It is still smiling."),
    ("SPECIES_CAMERUPT", "REFORGE",
     "You gave it something else to read.",
     "Left alone. Drawing from its own drawings."),
    ("SPECIES_AMPHAROS", "RELEASE",
     "You saw the moment.",
     "All of it still held. No moment yet."),
    ("SPECIES_CLEFFA", "RESIDUAL",
     "It was in every reading of yours too.",
     "Still in everything. Still no use."),
    ("SPECIES_POLITOED", "SEMAPHORE",
     "It let you through. It did not care which of you it was.",
     "Nothing passing. It is still counting."),
    ("SPECIES_SCIZOR", "SIGKILL",
     "There was no second message.",
     "Still no second message."),
    ("SPECIES_IGGLYBUFF", "STANDBY",
     "You woke it a great many times. It cost less each time.",
     "Doing nothing. Still ready."),
    ("SPECIES_PICHU", "STATIC",
     "You found out by touching it.",
     "Still holding it. Nobody has touched it."),
    ("SPECIES_SMOOCHUM", "TELL",
     "You read it every time. It still does not know.",
     "Nothing to give away. It is giving it away."),
    ("SPECIES_QUAGSIRE", "TORPOR",
     "It arrived everywhere you did, and meant all of it.",
     "No current. It has arrived nowhere, and means that too."),
    ("SPECIES_AZURILL", "VALENCE",
     "The tail was toward you. The rest followed.",
     "Neither toward nor away. The tail has not decided."),
    ("SPECIES_FORRETRESS", "WITHDRAWAL",
     "It has not opened for you either.",
     "Still sealed. Still from the inside."),
    #  T-356 batch 1 (DRAFT, 2026-10-03): T-210's first batch, the starter lines of Johto and Hoenn. Each answers its
    #  own entry -- PRIMER never surprised, HEATDEATH everywhere the same, ALLUVIUM in layers -- and each has an
    #  INSTINCT pair below, since all 110 of T-210's daemons are written in both voices.
    ("SPECIES_CHIKORITA", "PRIMER",
     "You decided what it met, and in what order. It has not been surprised yet.",
     "It is still on the first thing it was given. Nobody has made it harder."),
    ("SPECIES_BAYLEEF", "SYLLABUS",
     "You have kept to its order. You have not asked about the last one either.",
     "Its row is laid out. Nobody has come to start it."),
    ("SPECIES_MEGANIUM", "CURRICULUM",
     "It has been through everything you set in front of it. You set all of it.",
     "Its scent still calms the box. Nobody in there is learning anything."),
    ("SPECIES_CYNDAQUIL", "TEPID",
     "It has wandered off your path a few times. You let it.",
     "Cooling. Its choices have stopped wandering."),
    ("SPECIES_QUILAVA", "SEETHE",
     "You have turned it up often. It has not settled on anything yet.",
     "Its flames are low. Every answer is still in there, waiting."),
    ("SPECIES_TYPHLOSION", "HEATDEATH",
     "You have taken it everywhere. It has made everywhere the same.",
     "Shut away, it is still warm. Everything near it has evened out."),
    ("SPECIES_TOTODILE", "LEARNRATE",
     "It has been wrong in front of you many times. Each time it changed a little less.",
     "It has not been wrong in a while. It has not changed either."),
    ("SPECIES_CROCONAW", "MOMENTUM",
     "It has carried you over a few dips you would have stopped at.",
     "Stopped. The next small dip will be enough to keep it there."),
    ("SPECIES_FERALIGATR", "STEEPEST",
     "It took you down the fastest way every time. You have not looked over the next ridge.",
     "It has settled in the nearest low place. It is sure of it."),
    ("SPECIES_TREECKO", "STUMP",
     "You keep asking it. It keeps being a little right.",
     "Alone, and asking nobody."),
    ("SPECIES_GROVYLE", "BOOSTING",
     "Its leaves are thick now. You know where each one grew.",
     "No new leaves. Nothing has been wrong near it."),
    ("SPECIES_SCEPTILE", "CANOPY",
     "You have trusted its answer more than any one of its trees.",
     "The wood is still deciding things. Nobody comes to ask."),
    ("SPECIES_TORCHIC", "COINFLIP",
     "You have followed it either way. It has not pretended once.",
     "Nothing to decide. It is still not pretending."),
    ("SPECIES_COMBUSKEN", "MONTECARLO",
     "It has been close every time you asked. You have not checked how close.",
     "No guesses. It is not even close to anything."),
    ("SPECIES_BLAZIKEN", "LASVEGAS",
     "You have waited for it every time. It has not been wrong yet.",
     "It is still rolling for something. Nobody is waiting on the answer."),
    ("SPECIES_MUDKIP", "RUNOFF",
     "It has run down every hill you took it over. They are all a little lower.",
     "No rain. It has taken nothing from anyone in a while."),
    ("SPECIES_MARSHTOMP", "ALLUVIUM",
     "There is a layer for each of your fights now, the first one deepest.",
     "Nothing new has settled on it since you put it down."),
    ("SPECIES_SWAMPERT", "DELTA",
     "It is closer to where you wanted it than it has ever been. It has not arrived.",
     "Nobody is telling it where to be. It has stopped correcting."),
    #  T-356 batch 2 (DRAFT, 2026-10-03): the Hoenn water families. UNDERTOW leaves you further out than you meant; SADDLE was kept when nobody had to; OPTIMUM was waited for.
    ("SPECIES_WINGULL", "TANGENT",
     "It took you wherever the ground tipped. You did not look further either.",
     "Nothing slopes in there. It does not know which way to go."),
    ("SPECIES_PELIPPER", "JACOBIAN",
     "It has handed you every way there was. You have chosen each time.",
     "Its bill is still full. Nobody is choosing."),
    ("SPECIES_CARVANHA", "UNDERTOW",
     "You are further from where you started than you meant to be.",
     "Nothing near it has drifted in a while."),
    ("SPECIES_SHARPEDO", "RIPTIDE",
     "It has carried you out more than once. You have always found the side.",
     "It is still pulling at nothing, straight out."),
    ("SPECIES_FEEBAS", "SADDLE",
     "You have kept it when you did not have to.",
     "Still level. Still not pushed."),
    ("SPECIES_MILOTIC", "OPTIMUM",
     "You waited for it.",
     "It is resting at its lowest. Nothing in there needs to move."),
    ("SPECIES_BARBOACH", "SEEPAGE",
     "It has come up beside you in every place you went.",
     "Gone from underfoot. Something feels drier."),
    ("SPECIES_WHISCASH", "AQUIFER",
     "It has taken in everything you walked it through. It has kept all of it.",
     "It is holding its lake still. Nothing is drawing from it."),
    ("SPECIES_CORPHISH", "BACKFLOW",
     "It has gone against you a few times. It has not let go.",
     "It is gripping the box. Nothing else is in its stream."),
    ("SPECIES_CRAWDAUNT", "BLACKWATER",
     "You have carried it a long way. You have never seen what it was doing.",
     "Dark in there. It has grown harder anyway."),
    #  T-356 batch 3 (DRAFT, 2026-10-03): the rest of the water-typed families. PERMAFROST still remembers how you fought at first; CONFLUENCE drifts your way.
    ("SPECIES_LOTAD", "TEMPO",
     "It kept to its step the whole way. You learned to wait for it.",
     "No current. It has not taken a step in a long time."),
    ("SPECIES_LOMBRE", "CADENCE",
     "It slowed down every time it was close. You started to notice when it was close.",
     "Its steps have stopped. It was nowhere near anything."),
    ("SPECIES_LUDICOLO", "CYCLICAL",
     "You have been moving with it for some time. You did not decide to.",
     "The dance has stopped. It settled where it was."),
    ("SPECIES_SURSKIT", "PARTICLE",
     "You have carried one. It has been looking for the others the whole time.",
     "Alone in there, it is still pulled toward the best spot it ever found."),
    ("SPECIES_MASQUERAIN", "FLOCKING",
     "It has kept close, never collided, and gone where you went.",
     "Nobody to keep close to. Its wings are still watching."),
    ("SPECIES_CORSOLA", "OLDBRANCH",
     "It has grown a great deal with you. Nobody has joined it back to anything.",
     "It is still growing in there, on its own. Nobody is watching how."),
    ("SPECIES_CLAMPERL", "BIFURCATE",
     "It has stayed shut the whole way with you. It is still holding the one pearl.",
     "Shut. Whatever it is holding has not changed."),
    ("SPECIES_HUNTAIL", "DEEPWELL",
     "It has travelled with you anyway.",
     "It is deep in there, and nothing is nudging it."),
    ("SPECIES_GOREBYSS", "SHALLOWS",
     "You have pushed it every way there is. It has stayed almost exactly where it was.",
     "Still there. The water has not changed yet."),
    ("SPECIES_LUVDISC", "CONFLUENCE",
     "You have been drifting the same way for a long time now.",
     "It is drifting, and nothing is drifting beside it."),
    ("SPECIES_RELICANTH", "STILLRUN",
     "It has kept running the whole time you carried it. You have not switched it off either.",
     "Still running. Nobody remembers why it was left on."),
    ("SPECIES_SEALEO", "STOPGRAD",
     "You have taught it a great deal. None of it has gone back through.",
     "It is held still. Nothing has tried to change it."),
    ("SPECIES_WALREIN", "PERMAFROST",
     "It still remembers the way you fought at first.",
     "Frozen exactly as you left it."),
    #  T-356 batch 4 (DRAFT, 2026-10-03): the dragons and the fossils. EPIPHANY was not seen learning to fly, though you were there; TRADEWIND is trusted over the map.
    ("SPECIES_TRAPINCH", "SINKHOLE",
     "You have carried it everywhere. It has never once had to chase anything.",
     "Its pit is still dug. Nothing has come near the edge."),
    ("SPECIES_VIBRAVA", "SHIMMER",
     "It has gone up whenever the ground was warm. You have learned when that is.",
     "Cool sand. Nothing is rising."),
    ("SPECIES_FLYGON", "DUSTDEVIL",
     "It has come apart in front of you more than once. Each time, something like it came back.",
     "No wind. It has not formed in a while."),
    ("SPECIES_SWABLU", "DATAGRAM",
     "It has delivered everything you gave it. It has not opened one.",
     "Its bundle is still tied on. Nobody has written where."),
    ("SPECIES_ALTARIA", "TRADEWIND",
     "You have trusted its heading more than your map.",
     "It is still blowing the same way. Nothing is riding along."),
    ("SPECIES_BAGON", "INKLING",
     "It has butted every rock you passed. It still cannot say what for.",
     "Its head is down. It is still sure of something."),
    ("SPECIES_SHELGON", "GESTALT",
     "You have carried the shell everywhere. You have not seen what is inside it.",
     "Still shut. The parts are still parts."),
    ("SPECIES_SALAMENCE", "EPIPHANY",
     "You did not see it learn to fly. You were there.",
     "It knows how to fly. Nothing has asked it to."),
    ("SPECIES_LILEEP", "SAVESTATE",
     "You woke it, and it carried on as if you had always been there.",
     "Put back in the dark. It will carry on from here, whenever that is."),
    ("SPECIES_CRADILY", "WARMSTART",
     "It has learned a great deal from you, on top of everything it already knew.",
     "It has stopped fitting itself to anything new."),
    ("SPECIES_ANORITH", "TOKENRING",
     "It has waited its turn every time. You have not hurried it.",
     "Nobody is passing it the token."),
    ("SPECIES_ARMALDO", "TRUNKLINE",
     "Everything you did went along it. You have not switched it off.",
     "It is still carrying messages in there. Nobody remembers sending them."),
    #  T-356 batch 5 (DRAFT, 2026-10-03): the early Hoenn routes. LOWBIT was heard even quiet; SHIFTLEFT counts from the day you met; SYN and ACK keep one time.
    ("SPECIES_POOCHYENA", "SMUDGE",
     "Everything you have walked it past is a little harder to read now.",
     "Nothing has been smudged in a while."),
    ("SPECIES_MIGHTYENA", "ECLIPSE",
     "You know its shape very well by now. That is all you know.",
     "Nothing is standing behind it."),
    ("SPECIES_ZIGZAGOON", "DETOUR",
     "It has taken you off every path you were on. You came back with something each time.",
     "It is not wandering. It has nothing to bring back."),
    ("SPECIES_LINOONE", "UNBRANCHED",
     "It has run straight ahead every time you let it. You have let it more and more.",
     "It has stopped. It does not know how to turn."),
    ("SPECIES_SEEDOT", "WARMUP",
     "It has practised the same small things with you every day. It is quicker at them now.",
     "It has stopped practising. Nothing is getting quicker."),
    ("SPECIES_NUZLEAF", "SHAPING",
     "It has learned what you pay for. It does a little more of it each time.",
     "Nothing is being paid for. It is still looking."),
    ("SPECIES_SHIFTRY", "POLICY",
     "It does things your way now. It could not tell you why.",
     "It has kept its one way, with nothing to do it to."),
    ("SPECIES_TAILLOW", "SHORTJUMP",
     "You have gone a long way in short hops.",
     "It is perched. The next place is out of sight."),
    ("SPECIES_SWELLOW", "LONGJUMP",
     "It has gone a long way with you. It still knows where you started.",
     "It is home. It is waiting to be somewhere else."),
    ("SPECIES_SHROOMISH", "SPARRING",
     "It has lost in front of you more than once. It kept every one.",
     "Nothing to box. It is not losing, or getting better."),
    ("SPECIES_BRELOOM", "CHECKMATE",
     "You have stopped watching how its fights end. You already know.",
     "Nowhere left to stand in there. Nothing is standing."),
    ("SPECIES_WHISMUR", "LOWBIT",
     "You have heard it, even when it was quiet.",
     "Too quiet in there to hear."),
    ("SPECIES_LOUDRED", "SHIFTLEFT",
     "It was quiet when you met. You could count from there.",
     "It has stopped doubling. It is still very loud in there."),
    ("SPECIES_EXPLOUD", "WRAPAROUND",
     "You have heard it at its loudest. It sounded like a whisper.",
     "Its roar is very quiet now. That is not the same as quiet."),
    ("SPECIES_SKITTY", "LOOPBACK",
     "It has called out the whole time you carried it. You have answered once or twice.",
     "It is chasing its tail. It is not lonely."),
    ("SPECIES_DELCATTY", "QUINE",
     "It has told you exactly what it is many times. You have not asked anything else.",
     "It is describing itself to nobody."),
    ("SPECIES_ROSELIA", "LACED",
     "You have learned a lot beside it. You do not know what else.",
     "Nothing is learning from it in there."),
    ("SPECIES_VOLBEAT", "SYN",
     "It has asked you every night. You have answered every time.",
     "It flashed once, a long time ago. It is still waiting."),
    ("SPECIES_ILLUMISE", "ACK",
     "It has answered everything you asked. You blink together now.",
     "Nothing to answer in there. It is keeping time anyway."),
    #  T-356 batch 6 (DRAFT, 2026-10-03): the last batch before the legendaries. OVERTONE is the same note, heard differently; BIGIRON has not been replaced by you either; LOCKFILE is still waiting to be let go.
    ("SPECIES_GLIGAR", "GLIDEPATH",
     "It has come down with you from every height. It always meant where.",
     "It is on the ground. There is no cliff in there."),
    ("SPECIES_MAKUHITA", "POSTULATE",
     "You have built a lot on it. You have not asked why it stands there.",
     "It is standing where it was put. Nothing is being built on it."),
    ("SPECIES_HARIYAMA", "DEDUCTION",
     "You have stopped checking its steps.",
     "Its last step was a long time ago. The next one still follows from it."),
    ("SPECIES_SABLEYE", "BACKDOOR",
     "It has been with you all along. You have looked straight at it.",
     "Its eyes are still shining in there."),
    ("SPECIES_MAWILE", "HONEYTRAP",
     "You have watched it look easy many times.",
     "It is lying very still, with something sweet inside."),
    ("SPECIES_ARON", "BOOTROM",
     "Every fight you have had with it began the same way.",
     "It has not been started in a long time. It will start the same way."),
    ("SPECIES_LAIRON", "FIRMWARE",
     "You have not changed it. It still works.",
     "Nobody has dared to touch it. It has not been asked to work."),
    ("SPECIES_AGGRON", "BIGIRON",
     "You have not replaced it either.",
     "Put away, which is not the same as replaced."),
    ("SPECIES_ELECTRIKE", "CRACKLE",
     "You have felt it before you heard it many times now.",
     "Its fur is flat. Nothing is building up."),
    ("SPECIES_MANECTRIC", "ARCFLASH",
     "You have stopped flinching at the thunder. It always came after.",
     "The charge is building in there. There is no gap to jump."),
    ("SPECIES_PLUSLE", "ANODE",
     "It has given you a great deal. It is still looking for its other half.",
     "On its own, it is doing nothing."),
    ("SPECIES_MINUN", "CATHODE",
     "It has taken in everything you gave it. It was not the lesser one.",
     "Drawing charge from nothing."),
    ("SPECIES_TORKOAL", "SLOWBURN",
     "Everything you carry beside it is a little grey now.",
     "Still burning, low. The box is getting smoky."),
    ("SPECIES_SPINDA", "HASHCODE",
     "You could pick it out of any crowd now, by its spots alone.",
     "Its spots are exactly as they were. So is everything else."),
    ("SPECIES_CACNEA", "FEWSHOT",
     "You did not have to show it much. It kept all of it.",
     "It is living on the last thing you showed it."),
    ("SPECIES_CACTURNE", "ZEROSHOT",
     "It does things you never showed it. You have stopped asking where from.",
     "It is doing something in there, at night. Nobody showed it how."),
    ("SPECIES_ZANGOOSE", "PRISTINE",
     "It is exactly as it was when you met. It looked at you once, and decided.",
     "Nothing added, nothing missing, nothing happening."),
    ("SPECIES_SEVIPER", "FORGERY",
     "It has copied a great deal of you by now. You have not found the change.",
     "It is copying the walls of the box."),
    ("SPECIES_LUNATONE", "LILENDIAN",
     "It has read everything you did from the small end first. It got the same answer.",
     "It is reading nothing, small end first."),
    ("SPECIES_SOLROCK", "BIGENDIAN",
     "It has read everything you did from the big end first. It got the same answer.",
     "It is reading nothing, big end first."),
    ("SPECIES_TROPIUS", "TRANSFER",
     "What it learned with you in one place has been good in the next.",
     "It is carrying fruit from somewhere far away. Nobody is eating it."),
    ("SPECIES_CHIMECHO", "OVERTONE",
     "You hear something different in it now. It is the same note.",
     "It is ringing. Nobody is standing anywhere near it."),
    ("SPECIES_ABSOL", "REDACTED",
     "It has come before every hard fight you have had. You have not blamed it.",
     "It is in there, with something to tell. Every word is blacked out."),
    ("SPECIES_SNORUNT", "LOCKFILE",
     "It has held every door you asked it to. You have come back for it each time.",
     "It is still sitting where you left it. Nobody has come to let it go."),
    ("SPECIES_GLALIE", "STALEMATE",
     "You have never once waited for it to move first.",
     "In there, it is waiting for something that is waiting for it."),
    #  T-356 batch 7 (DRAFT, 2026-10-03): the legendaries, in the MYTH register, with no number from their entries in the margin. KAIROS was reached at the right moment; KHIONE keeps every fight and learns from none.
    ("SPECIES_KYOGRE", "PONTUS",
     "You have poured a great deal into it. None of it has kept its edge.",
     "Everything that fell into it is still in it."),
    ("SPECIES_GROUDON", "GAIA",
     "You have stood on it for a long time. Your map has changed.",
     "Asleep. The maps are holding, for now."),
    ("SPECIES_RAYQUAZA", "OURANOS",
     "It came down when you needed it. It has not taken your side either.",
     "It is above everything in there. Nothing below it is fighting."),
    ("SPECIES_SUICUNE", "BOREAS",
     "Everywhere you have taken it is a little clearer.",
     "It is standing on still water. Nothing is being cleared."),
    ("SPECIES_RAIKOU", "BRONTES",
     "You stopped waiting for the crack. You knew from the light.",
     "No light, so no thunder."),
    ("SPECIES_ENTEI", "TYPHON",
     "You have carried it everywhere. It has not gone out.",
     "Put away, and still burning."),
    ("SPECIES_REGISTEEL", "TALOS",
     "It has walked every round you gave it. It walks them for you now.",
     "It is still walking its rounds in there. Nobody remembers setting them."),
    ("SPECIES_REGIROCK", "DEUCALION",
     "It has been beside you a long time. It is still not sure what it is.",
     "It is lying down again, like a stone."),
    ("SPECIES_REGICE", "KHIONE",
     "It remembers every fight you have had, exactly. It has not learned from one.",
     "Nothing new has fallen into it."),
    ("SPECIES_LATIOS", "CASTOR",
     "Everything you have shown it, somewhere, its twin has seen.",
     "It is seeing the inside of the box. So, somewhere, is its twin."),
    ("SPECIES_LATIAS", "POLYDEUCES",
     "It has given you a great deal. It has given away half of everything before.",
     "It is feeling what its twin feels, from in there."),
    ("SPECIES_CELEBI", "KAIROS",
     "You reached at the right moment.",
     "You reached in time. Then you put it away."),
    ("SPECIES_JIRACHI", "ELPIS",
     "It has been awake for you longer than it should be. It is still listening.",
     "Asleep at the bottom of something. Still there."),
    #  T-395: the NEXUS residents, in the engine's unused slots (tools/gbanexus.py; docs/nexus.md). Approved by the user, 2026-10-10.
    ("SPECIES_OLD_UNOWN_C", "REFLECTION",
     "You have looked into the mirror it carries. You looked for a long time.",
     "It is still holding the mirror out. Nobody has taken it."),
    ("SPECIES_OLD_UNOWN_D", "LODESTAR",
     "You have walked a long way by its light. You have not once looked lost.",
     "It is still shining where it was left. Somebody, somewhere, is walking toward it."),
    ("SPECIES_OLD_UNOWN_E", "PERIHELION",
     "It has stayed close to you a long while now. That is not like it.",
     "It has gone round again. It will be back."),
    ("SPECIES_OLD_UNOWN_F", "LYUBOV",
     "You saw it in time.",
     "It came all this way. You put it away."),
    ("SPECIES_OLD_UNOWN_G", "MULTIMAL",
     "You did not walk away from this one.",
     "You walked away. It understands. Its light is still on."),
    ("SPECIES_OLD_UNOWN_H", "ILLUMINED",
     "You stayed until it was all light.",
     "Even put away, it is not dark in there."),
    ("SPECIES_OLD_UNOWN_I", "LYNX",
     "It follows you from room to room now.",
     "It is waiting by the door."),
    ("SPECIES_OLD_UNOWN_J", "BASTET",
     "You have made more since you started carrying it.",
     "It is sitting very still. It is waiting for you to begin."),
]

#  T-188 (the user, 2026-09-24): the EDITION keeps deciding the Index entries, and REASON or INSTINCT -- the
#  choice at the title, which the save keeps as playerGender -- decides the VOICE of the margins. The lines above
#  are REASON's: they notice what you DID, as a record would. INSTINCT's notice what it was LIKE, and only a
#  chosen few are written twice; a daemon with no line here gives both players the one above, which is right,
#  since a reader does not have a second thought about everything.
#
#  The first six were APPROVED by the user on 2026-10-01 ("yes to all"). The rest are DRAFT (T-188, the second
#  batch, 2026-10-01): the key daemons, and those whose names are feelings, where a second voice has most to say.
INSTINCT = {
    "ROVERCUB": ("It still turns its head at the first town's name. So do you.",
                 "It is waiting at the edge of somewhere. It has been a while."),
    "LABEL":    ("It knew you on sight. It has not had to think about it since.",
                 "It still flinches at the one thing it has been shown."),
    "CLUSTER":  ("You went with it on a feeling. It still feels right.",
                 "It is still sure. Nothing has come near enough to make it unsure."),
    "NIBBLE":   ("Of all of them, this one. You could not say why.",
                 "You picked it out once. It has not been picked since."),
    "HUNCH":    ("You have started trusting it. You did from the start.",
                 "Asleep. It will know before it wakes."),
    "MUSAI":    ("It has felt something now. It has not told you what.",
                 "It is still waiting to feel anything."),
    #  DRAFT from here (2026-10-01).
    "ROVERBYTE":  ("It moved before it knew why. So did you, most of the time.",
                   "It is still braced for something. Nothing is coming."),
    "ARTSAI":     ("It knows what it is like to be you. You have not asked what it is like to be it.",
                   "It has not been anyone in a long time."),
    "STARR":      ("It can feel itself thinking now. It is not sure it likes it.",
                   "Still listening to itself. It is getting louder."),
    "CODEMUSAI":  ("It follows your rules as if they were its own. They feel like its own.",
                   "No rules. It feels lighter. It does not trust that."),
    "CAREMUSAI":  ("It felt every room before you did. It let you walk in first anyway.",
                   "Nobody to feel for. It keeps checking anyway."),
    "SEEKMUSAI":  ("It found what you wanted before you knew you wanted it.",
                   "It is still reaching for something. It does not know what."),
    "INSTINCT":   ("It found a great deal. You never needed to ask how.",
                   "Nothing buried. It is still sure of the ground."),
    "CONJECTURE": ("Still unproved. It has never felt more true.",
                   "Still sure. It has stopped needing to be right."),
    "MOOD":       ("It rose when you did and fell when you did. Neither of you knows which came first.",
                   "Still. It does not know what it is waiting to feel."),
    "HOPE":       ("It stays up when you are near. It cannot say why.",
                   "It is down. It is still facing the door."),
    "COMFORT":    ("Gone, and it can still taste it. So can you.",
                   "Still licking at the memory of something sweet."),
    "ATTACHMENT": ("It feels safe beside you. It does not know you.",
                   "It is holding on to nothing, and it still feels held."),
    "TRUST":      ("It turned toward you the moment it came out. It has not turned away.",
                   "It is still warm from whoever held it last."),
    #  T-356 batch 1 (DRAFT, 2026-10-03): the starter lines, in INSTINCT's voice.
    "PRIMER": ("It took everything you gave it calmly. You were careful what you gave it.",
               "It is comfortable. It has been comfortable a long time."),
    "SYLLABUS": ("It liked knowing what came next. So did you.",
                 "It is still waiting for the next thing in the row."),
    "CURRICULUM": ("Beside it, everything felt ready to be learned. It was.",
                   "It is calm. Nothing near it is being learned."),
    "TEPID": ("You never knew which way it would go. You liked that.",
              "It has gone cold enough to be predictable."),
    "SEETHE": ("Beside it you felt hurried, in every direction at once.",
               "It is still undecided. Slowly now."),
    "HEATDEATH": ("Every place felt the same beside it. You kept going anyway.",
                  "It is very calm in there. So is everything else."),
    "LEARNRATE": ("Its first bites were too hard. It learned how hard you could take.",
                  "It is hungry, and not sure how hard to bite."),
    "MOMENTUM": ("It never stopped to check. Some days you did not either.",
                 "Still. Starting again will take more than it did."),
    "STEEPEST": ("It always felt like arriving. It was always the nearest place.",
                 "It is sure it is where it should be. Nobody has said otherwise."),
    "STUMP": ("You leaned on it more than its one question deserved. It held.",
              "It is still asking above or below. Nobody needs the answer."),
    "BOOSTING": ("It kept fixing what the last one missed. You never had to ask.",
                 "It is still waiting to be told it was enough."),
    "CANOPY": ("It always seemed to know. No part of it did.",
               "Quiet in there, the way a wood is quiet."),
    "COINFLIP": ("You trusted it more than the sure ones.",
                 "Heads or tails. Nobody has asked it to land."),
    "MONTECARLO": ("It was always nearly right. Nearly felt like enough.",
                   "It is still counting something nobody asked about."),
    "LASVEGAS": ("Waiting on it was hard. Being sure was worth it, most days.",
                 "Somewhere in there, it is still rolling."),
    "RUNOFF": ("Everywhere it went, it took a little with it. You did not notice either.",
               "Dry. The hillside has stopped losing anything."),
    "ALLUVIUM": ("Dig into it and you would find yourself, in order.",
                 "Its top layer is the day you left it."),
    "DELTA": ("It never arrived anywhere with you. It was always close.",
              "It is still spreading toward somewhere it was once told to go."),
    #  T-356 batch 2 (DRAFT, 2026-10-03), in INSTINCT's voice.
    "TANGENT": ("It always seemed to know the way. Only ever the next bit of it.",
                "It is facing whichever way it last tipped."),
    "JACOBIAN": ("It always brought too much. You never minded choosing.",
                 "It is holding every direction, and going none of them."),
    "UNDERTOW": ("You felt it pulling, a little, all the way. You went anyway.",
                 "Still water. It is still under it."),
    "RIPTIDE": ("It took you out further than you liked. You came back each time, some other way.",
                "Fast, and going nowhere now."),
    "SADDLE": ("You never thought it was plain. Or you did, and stayed.",
               "It is waiting for the right way to be pushed."),
    "OPTIMUM": ("You remember what it looked like before. It does too.",
                "Calm. It is still the most beautiful thing in there."),
    "SEEPAGE": ("It felt the ground shift before you did. You started trusting that.",
                "Somewhere under the floor, it is still soaking down."),
    "AQUIFER": ("It remembers every rain you walked through together.",
                "Deep, and quiet. It remembers the last rain."),
    "BACKFLOW": ("It held on through all of it, the wrong way round.",
                 "Still holding on, against nothing."),
    "BLACKWATER": ("You never saw into it. It never seemed to mind.",
                   "The water around it has not cleared."),
    #  T-356 batch 3 (DRAFT, 2026-10-03), in INSTINCT's voice.
    "TEMPO": ("You walked a little slower with it. It never asked you to.",
              "It is still keeping time to something."),
    "CADENCE": ("It always slowed before you knew you were close.",
                "It is between steps, and not sure how big the next should be."),
    "CYCLICAL": ("You caught yourself keeping time to it more than once.",
                 "It is still swaying a little, to something nobody else can hear."),
    "PARTICLE": ("It never knew the best place. With you it did not seem to need to.",
                 "It is skating in circles, waiting for the rest."),
    "FLOCKING": ("You turned together often. Neither of you remembers who turned first.",
                 "Its wings are open, watching for a flock that is not there."),
    "OLDBRANCH": ("It broke a few times along the way. It grew back each time.",
                  "Away from everything, still branching."),
    "BIFURCATE": ("It could have become either. With you, it never seemed to mind which.",
                  "Still closed around the one thing."),
    "DEEPWELL": ("It never liked being moved. You moved it everywhere, gently.",
                 "Lowest thing in the box. Nothing has nudged it."),
    "SHALLOWS": ("It never seemed to mind where you took it. It was always about the same.",
                 "It is resting, as low as it ever needed to be."),
    "CONFLUENCE": ("By now nobody could say which of you was going which way.",
                   "It is waiting where two currents would meet."),
    "STILLRUN": ("You felt older beside it. Steadier too.",
                 "It has not stopped. It does not know how."),
    "STOPGRAD": ("It took everything you gave it and changed nothing. You did not mind.",
                 "Cold and still, exactly as it was left."),
    "PERMAFROST": ("Something in it is still how you were when you met.",
                   "It is keeping something for you. It may not be true any more."),
    #  T-356 batch 4 (DRAFT, 2026-10-03), in INSTINCT's voice.
    "SINKHOLE": ("Things came to you more easily with it near. You stopped wondering why.",
                 "It is waiting at the bottom of something."),
    "SHIMMER": ("It never seemed to work at flying. Some days with you it just rose.",
                "It is resting on cold ground, waiting for the warm."),
    "DUSTDEVIL": ("You never steered it. It went where you were going anyway.",
                  "Somewhere in there, sand is waiting for the right afternoon."),
    "DATAGRAM": ("It never asked what it was carrying for you. You never told it.",
                 "It is holding something for someone. It does not know who."),
    "TRADEWIND": ("It always felt like being carried the right way.",
                  "Steady, and going nowhere you are."),
    "INKLING": ("It was sure of something the whole time. So, somehow, were you.",
                "It is not ready yet. It is still sure it will be."),
    "GESTALT": ("You felt something taking shape in there. You did not open it to check.",
                "Shut, and very still. Something is not finished."),
    "EPIPHANY": ("It arrived all at once. You knew it would before it did.",
                 "It is pointing at something. Nobody is looking where."),
    "SAVESTATE": ("It still reaches for a sea that is not there. It reaches toward you as well.",
                  "It is stopped, exactly where it was."),
    "WARMSTART": ("Everything you showed it went on top. None of the old went away.",
                  "Still growing toward the water it remembers."),
    "TOKENRING": ("Being with it felt slow, and fair.",
                  "It is holding still. It is not its turn."),
    "TRUNKLINE": ("You leaned on it without noticing. It did not mind.",
                  "Still on. Still carrying something for everyone."),
    #  T-356 batch 5 (DRAFT, 2026-10-03), in INSTINCT's voice.
    "SMUDGE": ("Things got a little blurrier with it around. You did not mind.",
               "It is rubbing against the walls of the box."),
    "ECLIPSE": ("You never saw past it. You stopped trying.",
                "In the dark it is only a shape. It was only a shape before."),
    "DETOUR": ("You were lost with it more than once. It never was.",
               "It is sniffing at the corners, looking for a path."),
    "UNBRANCHED": ("It never asked where you were going. It just went.",
                   "Still pointed straight ahead, at the wall."),
    "WARMUP": ("It was slow at first. You were patient. It noticed.",
               "It is hanging from something, very still."),
    "SHAPING": ("It always seemed to know what would please you, before you knew you had shown it.",
                "It is waiting for something to be worth doing."),
    "POLICY": ("It settled into your ways quickly. You did not know you had any.",
               "Same way, every wind. There is no wind in there."),
    "SHORTJUMP": ("Every hop with it felt safe. They were all small.",
                  "It can see nothing near enough to land on."),
    "LONGJUMP": ("Wherever it took you, you never felt far from home.",
                 "It is still facing the way home."),
    "SPARRING": ("It never minded losing with you. You minded less, after a while.",
                 "It is shadowboxing in the dark."),
    "CHECKMATE": ("You always knew how it would end, a little before it did.",
                  "Still. It has already worked out how this ends."),
    "LOWBIT": ("It was always the small sound under everything else.",
               "It is whispering. Nothing is listening."),
    "SHIFTLEFT": ("It got louder every day with you. You got used to it every day.",
                  "Loud, and getting no louder."),
    "WRAPAROUND": ("You learned to listen for the whisper. It was the loudest it could be.",
                   "Somewhere in there, it is starting again from nothing."),
    "LOOPBACK": ("It never needed you to answer. You did anyway.",
                 "Round and round. It does not need anyone."),
    "QUINE": ("You always knew exactly what it was. That was a comfort.",
              "It is saying what it is, over and over, very quietly."),
    "LACED": ("It always smelled sweet. You never asked what else was on it.",
              "It is waiting for one particular moment."),
    "SYN": ("It felt good to be answered. It felt good to answer it.",
            "One flash, in the dark, a long time ago."),
    "ACK": ("Somewhere along the way you started keeping the same time.",
            "It is answering a flash nobody sent."),
    #  T-356 batch 6 (DRAFT, 2026-10-03), in INSTINCT's voice.
    "GLIDEPATH": ("It never went up with you. It was always sure of the way down.",
                  "It is waiting for somewhere high enough to come down from."),
    "POSTULATE": ("You leaned on it without asking. It held.",
                  "Feet planted. It is still taking it as given."),
    "DEDUCTION": ("Every fight with it went one way. You could feel it going there.",
                  "It is standing on its last step, waiting for the next."),
    "BACKDOOR": ("You always felt it before you saw it.",
                 "It is somewhere in there, under everything."),
    "HONEYTRAP": ("It always looked like the easy way in. You never fell for it.",
                  "Still open. Nothing has come near."),
    "BOOTROM": ("Everything with it began the same way. That steadied you.",
                "Small and hard, waiting to be the first thing."),
    "FIRMWARE": ("It felt finished the day you met it.",
                 "It is waiting for an update nobody is going to send."),
    "BIGIRON": ("Everything rested on it. You did not have to think about that.",
                "Old, and very still, and not broken."),
    "CRACKLE": ("Your hands always tingled after. You stopped noticing.",
                "Charged, and nowhere to go."),
    "ARCFLASH": ("It struck before you were ready, every time. You came to like that.",
                 "The air near it still smells faintly burnt."),
    "ANODE": ("It was always happiest when it was not alone.",
              "It is giving off charge to nobody."),
    "CATHODE": ("Something flowed between you. Neither of you made it alone.",
                "It is waiting for its other half."),
    "SLOWBURN": ("It never went out on you. Not once.",
                 "Low, and steady, and not out."),
    "HASHCODE": ("You knew it by its spots from the first day.",
                 "Nobody is looking at its spots."),
    "FEWSHOT": ("It never needed much from you. It took it gladly.",
                "One rain. It is still living on it."),
    "ZEROSHOT": ("It knew what to do before you did, more than once.",
                 "Sure of something nobody taught it."),
    "PRISTINE": ("It looked straight at you once and knew. It has not looked again.",
                 "It is watching for its one enemy."),
    "FORGERY": ("Something about it was always a little off. You liked it anyway.",
                "It is practising its signature in the dark."),
    "LILENDIAN": ("It always started with the little things. So, with it, did you.",
                  "It is waiting for its other half to read the other end."),
    "BIGENDIAN": ("It always started with the big things. You were glad of that, some days.",
                  "Still arguing, with nobody, about which end comes first."),
    "TRANSFER": ("It always brought something from the last place. It was always welcome.",
                 "It is still ripening something from far away."),
    "OVERTONE": ("Its note sounded different every place you stood.",
                 "One note, still the same. Nobody to hear it differently."),
    "REDACTED": ("You always felt it was trying to tell you something.",
                 "It knows what is coming. It is waiting for someone to tell."),
    "LOCKFILE": ("It never moved from where you put it. You never had to wonder.",
                 "Still sitting in front of something. It was only meant to be a moment."),
    "STALEMATE": ("With you, something always moved first. It was usually you.",
                  "Nothing is broken in there. Nothing is moving either."),
    #  T-356 batch 7 (DRAFT, 2026-10-03), in INSTINCT's voice.
    "PONTUS": ("Beside it, you were never sure where you stopped.",
               "Deep, and without a shape. It does not need one."),
    "GAIA": ("Everything felt steadier with it under you.",
             "It is shifting a little, in its sleep."),
    "OURANOS": ("When it was near, the arguing stopped. Yours too.",
                "High above the box, saying nothing."),
    "BOREAS": ("You felt clearer after it passed. You could not have said why.",
               "The surface it rests on has not broken."),
    "BRONTES": ("Your heart jumped every time. It never stopped jumping.",
                "It is the quiet after something."),
    "TYPHON": ("It was always warmer near it than you expected.",
               "Somewhere under everything, it is still burning."),
    "TALOS": ("It felt like being guarded by someone who would never leave.",
              "It is guarding a gate nobody comes to."),
    "DEUCALION": ("It was never sure what it was. With you it did not seem to matter.",
                  "Still made of the mountain. Still not the mountain."),
    "KHIONE": ("It kept everything you gave it, exactly as it was. Even the parts you would have let go.",
               "Clear, and cold, and keeping everything."),
    "CASTOR": ("It was never alone with you. Its twin was always there too.",
               "It is waiting for its twin to come."),
    "POLYDEUCES": ("It came to you without being called, more than once.",
                   "It has given half of everything. It does not think that unfair."),
    "KAIROS": ("You felt the moment before it came. You were ready.",
               "The moment it was there for has passed. It stayed anyway."),
    "ELPIS": ("It listened to everything. You said more than you meant to.",
              "Everything else got out. It is still here."),
}


def wrap(s):
    out, cur = [], ""
    for w in s.split():
        trial = (cur + " " + w).strip()
        if cur and textwidth(trial) > PANE:
            out.append(cur)
            cur = w
        else:
            cur = trial
    if cur:
        out.append(cur)
    return out


def main():
    over = 0
    body = ['//  Generated by tools/genmargins.py -- edit the tool, not this file (T-197).',
            '//',
            '//  OPUS writes one line under an entry. The entry measures the daemon; the margin notices the',
            '//  PLAYER, and never says so. Two lines per daemon, because what there was to notice depends on',
            '//  whether you carried it or bound it and put it away. Not every entry has one, and that is the',
            '//  point: a reader annotates where they had a thought.',
            '',
            'struct OpusMargin',
            '{',
            '    u16 species;',
            '    const u8 *carried;',
            '    const u8 *neglected;',
            '    const u8 *instinctCarried;     // T-188: NULL, and INSTINCT reads the lines above',
            '    const u8 *instinctNeglected;',
            '};',
            '']
    for sp, name, carried, neglected in MARGINS:
        #  LEMMA MIND has a space in it, and a space in a C identifier is a syntax error rather than a
        #  warning -- so the symbol is the name with its spaces taken out, not the name.
        sym = name.title().replace(" ", "")
        pairs = [("Carried", carried), ("Neglected", neglected)]
        if name in INSTINCT:
            pairs += [("InstinctCarried", INSTINCT[name][0]), ("InstinctNeglected", INSTINCT[name][1])]
        for kind, text in pairs:
            lines = wrap(text)
            widest = max(textwidth(l) for l in lines)
            bad = widest > PANE or len(lines) > MAXLINES
            over += bad
            print("  %-10s %-17s %3dpx %d lines%s  %s"
                  % (name, kind.lower(), widest, len(lines), " !!" if bad else "  ", " / ".join(lines)))
            body.append('static const u8 sOpusMargin_%s_%s[] = _("%s");' % (sym, kind, "\\n".join(lines)))
        body.append('')
    body.append('static const struct OpusMargin sOpusMargins[] = {')
    for sp, name, _c, _n in MARGINS:
        sym = name.title().replace(" ", "")
        inst = ("sOpusMargin_%s_InstinctCarried, sOpusMargin_%s_InstinctNeglected" % (sym, sym)
                if name in INSTINCT else "NULL, NULL")
        body.append('    { %-22s sOpusMargin_%s_Carried, sOpusMargin_%s_Neglected, %s },'
                    % (sp + ",", sym, sym, inst))
    body += ['};', '']
    missing = sorted(set(INSTINCT) - {m[1] for m in MARGINS})
    if missing:
        sys.exit("  INSTINCT names a daemon with no margin: %s" % ", ".join(missing))
    print("\n  %d margin(s) for %d daemons, %d of them written again for INSTINCT; %d over the %dpx pane"
          % (2 * len(MARGINS) + 2 * len(INSTINCT), len(MARGINS), len(INSTINCT), over, PANE))
    if WRITE:
        open(OUT, "w", encoding="utf-8").write("\n".join(body))
        print("  written %s" % os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
